<%@ page import="org.json.JSONArray" %>
<%
String[] authors = 
{
    "Abbott, Edwin A.",
    "Aeschylus",
    "Aesop",
    "Amundsen, Roald",
    "Archimedes",
    "Aristophanes",
    "Aristotle",
    "Augustine of Hippo",
    "Austen, Jane",
    "Bacon, Francis",
    "Balzac, Honore de",
    "Banfield, Edmund James",
    "Baudelaire, Charles",
    "Beckford, William",
    "Beeton, Isabella",
    "Behn, Aphra",
    "Berkeley, George",
    "The King James Bible",
    "Bird, Isabella L.",
    "Blackmore, R. D.",
    "Blaxland, Gregory",
    "Boccaccio, Giovanni",
    "Boldrewood, Rolf",
    "Borrow, George",
    "Boswell, James",
    "Brillat-Savarin",
    "Bronte, Anne",
    "Bronte, Charlotte",
    "Bronte, Emily",
    "Buchan, John",
    "Bulfinch, Thomas",
    "Burckhardt, John Lewis",
    "Burke, Edmund",
    "Burton, Richard Francis, Sir",
    "Butler, Samuel",
    "Campanella, Tommaso",
    "Cao Xueqin",
    "Carroll, Lewis",
    "Casanova, Giacomo",
    "Catullus",
    "Cervantes, Miguel de",
    "Chaucer, Geoffrey",
    "Chekhov, Anton",
    "Chesterton, G. K.",
    "Cholmondeley, Mary, 1859-1925",
    "Cicero, Marcus Tullius",
    "Clarke, Marcus",
    "Cleland, John",
    "Collins, Wilkie",
    "Confucius",
    "Conrad, Joseph",
    "Cook, James,",
    "Copernicus, Nicolaus",
    "Cousin, John William",
    "Dante",
    "Darwin, Charles",
    "Defoe, Daniel",
    "Descartes, Rene",
    "Dickens, Charles",
    "Donne, John",
    "Doré, Gustave",
    "Dostoyevsky, Fyodor",
    "Doyle, Arthur Conan, Sir",
    "Dreiser, Theodore",
    "Dryden, John",
    "Durer, Albrecht",
    "Dumas, Alexandre, père,",
    "Dumas, Alexandre, fils,",
    "Edgeworth, Maria",
    "Eliot, George",
    "Emerson, Ralph Waldo",
    "Epictetus",
    "Epicurus",
    "Desiderius Erasmus of Rotterdam",
    "Euclid",
    "Euripides",
    "Eyre, Edward John",
    "Fa-Hien or Fa-hsien",
    "Fielding, Henry",
    "Firdausi",
    "Fiske, John",
    "Fitzgerald, F. Scott",
    "Flaubert, Gustave",
    "Frazer, Sir James George",
    "Gaboriau, Émile",
    "Galen",
    "Galileo Galilei",
    "Galsworthy, John",
    "Gay, John",
    "Gibbon, Edward",
    "Giles, Ernest",
    "Gissing, George",
    "Green, Anna Katharine",
    "Grimm, Jakob",
    "Gogol, Nikolai",
    "Goldsmith, Oliver",
    "Gorky, Maksim",
    "Hakluyt, Richard",
    "Hamsun, Knut",
    "Hardy, Thomas",
    "Harvey, William",
    "Hawthorne, Nathaniel",
    "Hentzner, Paul",
    "Herodotus",
    "Hegel, Georg Wilhelm Friedrich",
    "Hesiod",
    "Hippocrates",
    "Hobbes, Thomas",
    "Hodgson, William Hope",
    "Holmes, Oliver Wendell",
    "Homer",
    "Housman, A. E.",
    "Howells, William Dean",
    "Hudson, William Henry",
    "Hugo, Victor",
    "Hume, David",
    "Hume, Fergus",
    "Huxley, Thomas Henry",
    "Ibsen, Henrik",
    "Irving, Washington",
    "James, Henry",
    "James, William",
    "Jardine, Frank",
    "Jenner, Edward,",
    "Johnson, Samuel",
    "Joyce, James",
    "Kafka, Franz",
    "Kant, Immanuel",
    "Keats, John",
    "Kepler, Johannes",
    "Keynes, John Maynard",
    "Kinglake, Alexander William",
    "Kingsley, Mary Henrietta",
    "Kipling, Rudyard",
    "Lang, Andrew",
    "Lawrence, D. H.",
    "Lawrence, T. E.",
    "Lao Tzu",
    "Le Fanu, Joseph Sheridan",
    "Leibniz, Gottfried Wilhelm",
    "Leichhardt, Ludwig",
    "Lermontov, Mikhail",
    "Lewis, Matthew",
    "Lewis, Sinclair",
    "Lister, Joseph",
    "Livingstone, David",
    "Locke, John",
    "Lucretius",
    "Lyell, Charles",
    "Machiavelli, Niccolò",
    "Malory, Thomas",
    "Malthus, Thomas",
    "Mandeville, John, Sir",
    "Marcus Aurelius",
    "Marlowe, Christopher",
    "Marx, Karl",
    "Maturin, Charles Robert",
    "Maupassant, Guy de",
    "Melville, Herman",
    "Meredith, George",
    "Merritt, Abraham",
    "Mill, John Stuart",
    "Milton, John",
    "Mitchell, Margaret",
    "Mitchell, Thomas",
    "Molière",
    "Montaigne, Michel de",
    "More, Thomas",
    "Moritz, Karl Philipp",
    "Morris, William",
    "Muskett, Philip E.",
    "Nesbit, E.",
    "Nietzsche, Friedrich",
    "Omar Khayyám",
    "Orwell, George",
    "Ovid",
    "Oxley, John",
    "Paine, Thomas",
    "Park, Mungo",
    "Pascal, Blaise",
    "Pasteur, Louis",
    "Plato",
    "Pliny, the Younger",
    "Plotinus",
    "Plutarch",
    "Polidori, John",
    "Pope, Alexander",
    "Poe, Edgar Allan",
    "Proust, Marcel",
    "Pushkin, Aleksandr",
    "Quincey, Thomas de",
    "Rabelais, Francois",
    "Radcliffe, Ann",
    "Richardson, James",
    "Richardson, Henry Handel",
    "Rousseau, Jean-Jacques",
    "Saadi",
    "Sand, George",
    "Schreiner, Olive",
    "Schopenhauer, Arthur",
    "Scott, Walter, Sir",
    "Seneca, L. Annaeus",
    "Shackleton, Ernest",
    "Shakespeare, William",
    "Shaw, George Bernard",
    "Shelley, Mary",
    "Shelley, Percy Bysshe",
    "Smith, Adam",
    "Smollett, Tobias",
    "Sophocles",
    "Spenser, Edmund",
    "Benedict de Spinoza",
    "Stanley, Henry Morton",
    "Stendhal",
    "Sterne, Laurence",
    "Stevenson, Robert Louis",
    "Stoker, Bram",
    "Sturt, Charles",
    "Swift, Jonathan",
    "Tacitus, Cornelius",
    "Tench, Watkin",
    "Tennyson, Alfred",
    "Thackeray, William Makepeace",
    "Thoreau, Henry David",
    "Thucydides",
    "Tolstoy, Leo",
    "Trollope, Anthony",
    "Tucker, James",
    "Turgenev, Ivan",
    "Twain, Mark",
    "Uzanne, Octave",
    "Verne, Jules",
    "Virgil",
    "Voltaire",
    "Wallace, Alfred Russel",
    "Walpole, Horace",
    "Walpole, Hugh",
    "Walton, Izaak",
    "Wells, H. G.",
    "Wilde, Oscar",
    "Wollstonecraft, Mary",
    "Woolf, Virginia",
    "Xenophon",
    "Yeats, W. B.",
    "Zola, Emile"
};

    String author = request.getParameter("author");
    JSONArray authorArray = new JSONArray();
    if (author != null && !author.trim().equals("")) {
    	author = author.toLowerCase();
        for (int i=0; i<authors.length; i++) {
            if (authors[i].toLowerCase().startsWith(author)) {
                authorArray.put(authors[i]);
            }
        }
    }
    out.println(authorArray.toString());

%>