------------------------------------------------------------------------------
-- Awards: Clear PUBLIC permissions on database.
USE Awards
GO
REVOKE ALL ON [dbo].[dt_addtosourcecontrol] to public
REVOKE ALL ON [dbo].[dt_addtosourcecontrol_u] to public
REVOKE ALL ON [dbo].[dt_adduserobject] to public
REVOKE ALL ON [dbo].[dt_adduserobject_vcs] to public
REVOKE ALL ON [dbo].[dt_checkinobject] to public
REVOKE ALL ON [dbo].[dt_checkinobject_u] to public
REVOKE ALL ON [dbo].[dt_checkoutobject] to public
REVOKE ALL ON [dbo].[dt_checkoutobject_u] to public
REVOKE ALL ON [dbo].[dt_displayoaerror] to public
REVOKE ALL ON [dbo].[dt_displayoaerror_u] to public
REVOKE ALL ON [dbo].[dt_droppropertiesbyid] to public
REVOKE ALL ON [dbo].[dt_dropuserobjectbyid] to public
REVOKE ALL ON [dbo].[dt_generateansiname] to public
REVOKE ALL ON [dbo].[dt_getobjwithprop] to public
REVOKE ALL ON [dbo].[dt_getobjwithprop_u] to public
REVOKE ALL ON [dbo].[dt_getpropertiesbyid] to public
REVOKE ALL ON [dbo].[dt_getpropertiesbyid_u] to public
REVOKE ALL ON [dbo].[dt_getpropertiesbyid_vcs] to public
REVOKE ALL ON [dbo].[dt_getpropertiesbyid_vcs_u] to public
REVOKE ALL ON [dbo].[dt_isundersourcecontrol] to public
REVOKE ALL ON [dbo].[dt_isundersourcecontrol_u] to public
REVOKE ALL ON [dbo].[dt_removefromsourcecontrol] to public
REVOKE ALL ON [dbo].[dt_setpropertybyid] to public
REVOKE ALL ON [dbo].[dt_setpropertybyid_u] to public
REVOKE ALL ON [dbo].[dt_validateloginparams] to public
REVOKE ALL ON [dbo].[dt_validateloginparams_u] to public
REVOKE ALL ON [dbo].[dt_vcsenabled] to public
REVOKE ALL ON [dbo].[dt_verstamp006] to public
REVOKE ALL ON [dbo].[dt_whocheckedout] to public
REVOKE ALL ON [dbo].[dt_whocheckedout_u] to public
REVOKE ALL ON [dbo].[dtproperties] to public
REVOKE ALL ON [dbo].[syscolumns] to public
REVOKE ALL ON [dbo].[syscomments] to public
REVOKE ALL ON [dbo].[sysconstraints] to public
REVOKE ALL ON [dbo].[sysdepends] to public
REVOKE ALL ON [dbo].[sysfilegroups] to public
REVOKE ALL ON [dbo].[sysfiles] to public
REVOKE ALL ON [dbo].[sysforeignkeys] to public
REVOKE ALL ON [dbo].[sysfulltextcatalogs] to public
REVOKE ALL ON [dbo].[sysindexes] to public
REVOKE ALL ON [dbo].[sysindexkeys] to public
REVOKE ALL ON [dbo].[sysmembers] to public
REVOKE ALL ON [dbo].[sysobjects] to public
REVOKE ALL ON [dbo].[syspermissions] to public
REVOKE ALL ON [dbo].[sysprotects] to public
REVOKE ALL ON [dbo].[sysreferences] to public
REVOKE ALL ON [dbo].[syssegments] to public
REVOKE ALL ON [dbo].[systypes] to public
REVOKE ALL ON [dbo].[sysusers] to public
GO
------------------------------------------------------------------------------
-- master: Clear PUBLIC permissions on database.
USE master
GO
REVOKE ALL ON [INFORMATION_SCHEMA].[CHECK_CONSTRAINTS] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[COLUMN_DOMAIN_USAGE] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[COLUMN_PRIVILEGES] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[COLUMNS] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[CONSTRAINT_COLUMN_USAGE] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[CONSTRAINT_TABLE_USAGE] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[DOMAIN_CONSTRAINTS] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[DOMAINS] to public
REVOKE ALL ON [system_function_schema].[fn_chariswhitespace] to public
REVOKE ALL ON [system_function_schema].[fn_escapecmdshellsymbols] to public
REVOKE ALL ON [system_function_schema].[fn_escapecmdshellsymbolsremovequotes] to public
REVOKE ALL ON [system_function_schema].[fn_generateparameterpattern] to public
REVOKE ALL ON [system_function_schema].[fn_helpcollations] to public
REVOKE ALL ON [dbo].[fn_isreplmergeagent] to public
REVOKE ALL ON [system_function_schema].[fn_listextendedproperty] to public
REVOKE ALL ON [dbo].[fn_MSFullText] to public
REVOKE ALL ON [dbo].[fn_MSgensqescstr] to public
REVOKE ALL ON [dbo].[fn_MSsharedversion] to public
REVOKE ALL ON [system_function_schema].[fn_removeparameterwithargument] to public
REVOKE ALL ON [system_function_schema].[fn_repladjustcolumnmap] to public
REVOKE ALL ON [system_function_schema].[fn_replbitstringtoint] to public
REVOKE ALL ON [system_function_schema].[fn_replcomposepublicationsnapshotfolder] to public
REVOKE ALL ON [system_function_schema].[fn_replgenerateshorterfilenameprefix] to public
REVOKE ALL ON [system_function_schema].[fn_replgetbinary8lodword] to public
REVOKE ALL ON [system_function_schema].[fn_replinttobitstring] to public
REVOKE ALL ON [system_function_schema].[fn_replmakestringliteral] to public
REVOKE ALL ON [system_function_schema].[fn_replprepadbinary8] to public
REVOKE ALL ON [system_function_schema].[fn_replquotename] to public
REVOKE ALL ON [system_function_schema].[fn_replrotr] to public
REVOKE ALL ON [system_function_schema].[fn_repltrimleadingzerosinhexstr] to public
REVOKE ALL ON [system_function_schema].[fn_repluniquename] to public
REVOKE ALL ON [system_function_schema].[fn_serverid] to public
REVOKE ALL ON [system_function_schema].[fn_servershareddrives] to public
REVOKE ALL ON [system_function_schema].[fn_skipparameterargument] to public
REVOKE ALL ON [dbo].[fn_sqlvarbasetostr] to public
REVOKE ALL ON [system_function_schema].[fn_updateparameterwithargument] to public
REVOKE ALL ON [dbo].[fn_varbintohexstr] to public
REVOKE ALL ON [dbo].[fn_varbintohexsubstring] to public
REVOKE ALL ON [system_function_schema].[fn_virtualfilestats] to public
REVOKE ALL ON [system_function_schema].[fn_virtualservernodes] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[KEY_COLUMN_USAGE] to public
REVOKE ALL ON [dbo].[MS_sqlctrs_users] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[PARAMETERS] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[REFERENTIAL_CONSTRAINTS] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[ROUTINE_COLUMNS] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[ROUTINES] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[SCHEMATA] to public
REVOKE ALL ON [dbo].[sp_ActiveDirectory_Obj] to public
REVOKE ALL ON [dbo].[sp_ActiveDirectory_SCP] to public
REVOKE ALL ON [dbo].[sp_ActiveDirectory_Start] to public
REVOKE ALL ON [dbo].[sp_addalias] to public
REVOKE ALL ON [dbo].[sp_addapprole] to public
REVOKE ALL ON [dbo].[sp_addarticle] to public
REVOKE ALL ON [dbo].[sp_addextendedproperty] to public
REVOKE ALL ON [dbo].[sp_addgroup] to public
REVOKE ALL ON [dbo].[sp_addlinkedserver] to public
REVOKE ALL ON [dbo].[sp_addlinkedsrvlogin] to public
REVOKE ALL ON [dbo].[sp_addlogin] to public
REVOKE ALL ON [dbo].[sp_addmergealternatepublisher] to public
REVOKE ALL ON [dbo].[sp_addmergearticle] to public
REVOKE ALL ON [dbo].[sp_addmergefilter] to public
REVOKE ALL ON [dbo].[sp_addmergepublication] to public
REVOKE ALL ON [dbo].[sp_addmergepullsubscription] to public
REVOKE ALL ON [dbo].[sp_addmergepullsubscription_agent] to public
REVOKE ALL ON [dbo].[sp_addmergesubscription] to public
REVOKE ALL ON [dbo].[sp_addmessage] to public
REVOKE ALL ON [dbo].[sp_addpublication] to public
REVOKE ALL ON [dbo].[sp_addpublication_snapshot] to public
REVOKE ALL ON [dbo].[sp_addpullsubscription] to public
REVOKE ALL ON [dbo].[sp_addpullsubscription_agent] to public
REVOKE ALL ON [dbo].[sp_addqueued_artinfo] to public
REVOKE ALL ON [dbo].[sp_addremotelogin] to public
REVOKE ALL ON [dbo].[sp_addrole] to public
REVOKE ALL ON [dbo].[sp_addrolemember] to public
REVOKE ALL ON [dbo].[sp_addscriptexec] to public
REVOKE ALL ON [dbo].[sp_addserver] to public
REVOKE ALL ON [dbo].[sp_addsrvrolemember] to public
REVOKE ALL ON [dbo].[sp_addsubscription] to public
REVOKE ALL ON [dbo].[sp_addsynctriggers] to public
REVOKE ALL ON [dbo].[sp_addtabletocontents] to public
REVOKE ALL ON [dbo].[sp_addtype] to public
REVOKE ALL ON [dbo].[sp_addumpdevice] to public
REVOKE ALL ON [dbo].[sp_adduser] to public
REVOKE ALL ON [dbo].[sp_adjustpublisheridentityrange] to public
REVOKE ALL ON [dbo].[sp_altermessage] to public
REVOKE ALL ON [dbo].[sp_approlepassword] to public
REVOKE ALL ON [dbo].[sp_article_validation] to public
REVOKE ALL ON [dbo].[sp_articlecolumn] to public
REVOKE ALL ON [dbo].[sp_articlefilter] to public
REVOKE ALL ON [dbo].[sp_articlesynctranprocs] to public
REVOKE ALL ON [dbo].[sp_articleview] to public
REVOKE ALL ON [dbo].[sp_attach_db] to public
REVOKE ALL ON [dbo].[sp_attach_single_file_db] to public
REVOKE ALL ON [dbo].[sp_attachsubscription] to public
REVOKE ALL ON [dbo].[sp_autostats] to public
REVOKE ALL ON [dbo].[sp_bcp_dbcmptlevel] to public
REVOKE ALL ON [dbo].[sp_bindefault] to public
REVOKE ALL ON [dbo].[sp_bindrule] to public
REVOKE ALL ON [dbo].[sp_bindsession] to public
REVOKE ALL ON [dbo].[sp_blockcnt] to public
REVOKE ALL ON [dbo].[sp_browsemergesnapshotfolder] to public
REVOKE ALL ON [dbo].[sp_browsesnapshotfolder] to public
REVOKE ALL ON [dbo].[sp_catalogs] to public
REVOKE ALL ON [dbo].[sp_catalogs_rowset] to public
REVOKE ALL ON [dbo].[sp_change_subscription_properties] to public
REVOKE ALL ON [dbo].[sp_change_users_login] to public
REVOKE ALL ON [dbo].[sp_changearticle] to public
REVOKE ALL ON [dbo].[sp_changedbowner] to public
REVOKE ALL ON [dbo].[sp_changegroup] to public
REVOKE ALL ON [dbo].[sp_changemergearticle] to public
REVOKE ALL ON [dbo].[sp_changemergefilter] to public
REVOKE ALL ON [dbo].[sp_changemergepublication] to public
REVOKE ALL ON [dbo].[sp_changemergepullsubscription] to public
REVOKE ALL ON [dbo].[sp_changemergesubscription] to public
REVOKE ALL ON [dbo].[sp_changeobjectowner] to public
REVOKE ALL ON [dbo].[sp_changepublication] to public
REVOKE ALL ON [dbo].[sp_changesubscription] to public
REVOKE ALL ON [dbo].[sp_changesubscriptiondtsinfo] to public
REVOKE ALL ON [dbo].[sp_changesubstatus] to public
REVOKE ALL ON [dbo].[sp_check_constbytable_rowset] to public
REVOKE ALL ON [dbo].[sp_check_constraints_rowset] to public
REVOKE ALL ON [dbo].[sp_check_for_sync_trigger] to public
REVOKE ALL ON [dbo].[sp_check_publication_access] to public
REVOKE ALL ON [dbo].[sp_check_sync_trigger] to public
REVOKE ALL ON [dbo].[sp_checknames] to public
REVOKE ALL ON [dbo].[sp_cleanupdbreplication] to public
REVOKE ALL ON [dbo].[sp_column_privileges] to public
REVOKE ALL ON [dbo].[sp_column_privileges_ex] to public
REVOKE ALL ON [dbo].[sp_column_privileges_rowset] to public
REVOKE ALL ON [dbo].[sp_columns] to public
REVOKE ALL ON [dbo].[sp_columns_ex] to public
REVOKE ALL ON [dbo].[sp_columns_rowset] to public
REVOKE ALL ON [dbo].[sp_configure] to public
REVOKE ALL ON [dbo].[sp_convertwebtasks] to public
REVOKE ALL ON [dbo].[sp_copymergesnapshot] to public
REVOKE ALL ON [dbo].[sp_copysnapshot] to public
REVOKE ALL ON [dbo].[sp_copysubscription] to public
REVOKE ALL ON [dbo].[sp_createorphan] to public
REVOKE ALL ON [dbo].[sp_createstats] to public
REVOKE ALL ON [dbo].[sp_cursor] to public
REVOKE ALL ON [dbo].[sp_cursor_list] to public
REVOKE ALL ON [dbo].[sp_cursorclose] to public
REVOKE ALL ON [dbo].[sp_cursorexecute] to public
REVOKE ALL ON [dbo].[sp_cursorfetch] to public
REVOKE ALL ON [dbo].[sp_cursoropen] to public
REVOKE ALL ON [dbo].[sp_cursoroption] to public
REVOKE ALL ON [dbo].[sp_cursorprepare] to public
REVOKE ALL ON [dbo].[sp_cursorprepexec] to public
REVOKE ALL ON [dbo].[sp_cursorunprepare] to public
REVOKE ALL ON [dbo].[sp_databases] to public
REVOKE ALL ON [dbo].[sp_datatype_info] to public
REVOKE ALL ON [dbo].[sp_dbcmptlevel] to public
REVOKE ALL ON [dbo].[sp_dbfixedrolepermission] to public
REVOKE ALL ON [dbo].[sp_dboption] to public
REVOKE ALL ON [dbo].[sp_ddopen] to public
REVOKE ALL ON [dbo].[sp_defaultdb] to public
REVOKE ALL ON [dbo].[sp_defaultlanguage] to public
REVOKE ALL ON [dbo].[sp_denylogin] to public
REVOKE ALL ON [dbo].[sp_depends] to public
REVOKE ALL ON [dbo].[sp_describe_cursor] to public
REVOKE ALL ON [dbo].[sp_describe_cursor_columns] to public
REVOKE ALL ON [dbo].[sp_describe_cursor_tables] to public
REVOKE ALL ON [dbo].[sp_disableagentoffload] to public
REVOKE ALL ON [dbo].[sp_diskdefault] to public
REVOKE ALL ON [dbo].[sp_distcounters] to public
REVOKE ALL ON [dbo].[sp_dropalias] to public
REVOKE ALL ON [dbo].[sp_dropanonymousagent] to public
REVOKE ALL ON [dbo].[sp_dropapprole] to public
REVOKE ALL ON [dbo].[sp_droparticle] to public
REVOKE ALL ON [dbo].[sp_dropdevice] to public
REVOKE ALL ON [dbo].[sp_dropextendedproperty] to public
REVOKE ALL ON [dbo].[sp_dropgroup] to public
REVOKE ALL ON [dbo].[sp_droplinkedsrvlogin] to public
REVOKE ALL ON [dbo].[sp_droplogin] to public
REVOKE ALL ON [dbo].[sp_dropmergealternatepublisher] to public
REVOKE ALL ON [dbo].[sp_dropmergearticle] to public
REVOKE ALL ON [dbo].[sp_dropmergepublication] to public
REVOKE ALL ON [dbo].[sp_dropmergepullsubscription] to public
REVOKE ALL ON [dbo].[sp_dropmergesubscription] to public
REVOKE ALL ON [dbo].[sp_dropmessage] to public
REVOKE ALL ON [dbo].[sp_droporphans] to public
REVOKE ALL ON [dbo].[sp_droppublication] to public
REVOKE ALL ON [dbo].[sp_droppullsubscription] to public
REVOKE ALL ON [dbo].[sp_dropremotelogin] to public
REVOKE ALL ON [dbo].[sp_droprole] to public
REVOKE ALL ON [dbo].[sp_droprolemember] to public
REVOKE ALL ON [dbo].[sp_dropserver] to public
REVOKE ALL ON [dbo].[sp_dropsrvrolemember] to public
REVOKE ALL ON [dbo].[sp_dropsubscription] to public
REVOKE ALL ON [dbo].[sp_droptype] to public
REVOKE ALL ON [dbo].[sp_dropuser] to public
REVOKE ALL ON [dbo].[sp_enableagentoffload] to public
REVOKE ALL ON [dbo].[sp_enum_oledb_providers] to public
REVOKE ALL ON [dbo].[sp_enumcodepages] to public
REVOKE ALL ON [dbo].[sp_enumcustomresolvers] to public
REVOKE ALL ON [dbo].[sp_enumdsn] to public
REVOKE ALL ON [dbo].[sp_enumerrorlogs] to public
REVOKE ALL ON [dbo].[sp_enumfullsubscribers] to public
REVOKE ALL ON [dbo].[sp_eventlog] to public
REVOKE ALL ON [dbo].[sp_execute] to public
REVOKE ALL ON [dbo].[sp_executesql] to public
REVOKE ALL ON [dbo].[sp_expired_subscription_cleanup] to public
REVOKE ALL ON [dbo].[sp_fallback_MS_sel_fb_svr] to public
REVOKE ALL ON [dbo].[sp_fkeys] to public
REVOKE ALL ON [dbo].[sp_foreign_keys_rowset] to public
REVOKE ALL ON [dbo].[sp_foreignkeys] to public
REVOKE ALL ON [dbo].[sp_fulltext_catalog] to public
REVOKE ALL ON [dbo].[sp_fulltext_column] to public
REVOKE ALL ON [dbo].[sp_fulltext_database] to public
REVOKE ALL ON [dbo].[sp_fulltext_service] to public
REVOKE ALL ON [dbo].[sp_fulltext_table] to public
REVOKE ALL ON [dbo].[sp_generatefilters] to public
REVOKE ALL ON [dbo].[sp_get_distributor] to public
REVOKE ALL ON [dbo].[sp_getagentoffloadinfo] to public
REVOKE ALL ON [dbo].[sp_getapplock] to public
REVOKE ALL ON [dbo].[sp_getarticlepkcolbitmap] to public
REVOKE ALL ON [dbo].[sp_getbindtoken] to public
REVOKE ALL ON [dbo].[sp_GetMBCSCharLen] to public
REVOKE ALL ON [dbo].[sp_getqueuedrows] to public
REVOKE ALL ON [dbo].[sp_getschemalock] to public
REVOKE ALL ON [dbo].[sp_getsubscriptiondtspackagename] to public
REVOKE ALL ON [dbo].[sp_gettypestring] to public
REVOKE ALL ON [dbo].[sp_grant_publication_access] to public
REVOKE ALL ON [dbo].[sp_grantdbaccess] to public
REVOKE ALL ON [dbo].[sp_grantlogin] to public
REVOKE ALL ON [dbo].[sp_help] to public
REVOKE ALL ON [dbo].[sp_help_agent_default] to public
REVOKE ALL ON [dbo].[sp_help_agent_parameter] to public
REVOKE ALL ON [dbo].[sp_help_agent_profile] to public
REVOKE ALL ON [dbo].[sp_help_fulltext_catalogs] to public
REVOKE ALL ON [dbo].[sp_help_fulltext_catalogs_cursor] to public
REVOKE ALL ON [dbo].[sp_help_fulltext_columns] to public
REVOKE ALL ON [dbo].[sp_help_fulltext_columns_cursor] to public
REVOKE ALL ON [dbo].[sp_help_fulltext_tables] to public
REVOKE ALL ON [dbo].[sp_help_fulltext_tables_cursor] to public
REVOKE ALL ON [dbo].[sp_help_publication_access] to public
REVOKE ALL ON [dbo].[sp_helparticle] to public
REVOKE ALL ON [dbo].[sp_helparticlecolumns] to public
REVOKE ALL ON [dbo].[sp_helparticledts] to public
REVOKE ALL ON [dbo].[sp_helpconstraint] to public
REVOKE ALL ON [dbo].[sp_helpdb] to public
REVOKE ALL ON [dbo].[sp_helpdbfixedrole] to public
REVOKE ALL ON [dbo].[sp_helpdevice] to public
REVOKE ALL ON [dbo].[sp_helpdistpublisher] to public
REVOKE ALL ON [dbo].[sp_helpdistributiondb] to public
REVOKE ALL ON [dbo].[sp_helpdistributor] to public
REVOKE ALL ON [dbo].[sp_helpdistributor_properties] to public
REVOKE ALL ON [dbo].[sp_helpextendedproc] to public
REVOKE ALL ON [dbo].[sp_helpfile] to public
REVOKE ALL ON [dbo].[sp_helpfilegroup] to public
REVOKE ALL ON [dbo].[sp_helpgroup] to public
REVOKE ALL ON [dbo].[sp_helpindex] to public
REVOKE ALL ON [dbo].[sp_helplanguage] to public
REVOKE ALL ON [dbo].[sp_helplinkedsrvlogin] to public
REVOKE ALL ON [dbo].[sp_helplog] to public
REVOKE ALL ON [dbo].[sp_helplogins] to public
REVOKE ALL ON [dbo].[sp_helpmergealternatepublisher] to public
REVOKE ALL ON [dbo].[sp_helpmergearticle] to public
REVOKE ALL ON [dbo].[sp_helpmergearticlecolumn] to public
REVOKE ALL ON [dbo].[sp_helpmergecleanupwait] to public
REVOKE ALL ON [dbo].[sp_helpmergefilter] to public
REVOKE ALL ON [dbo].[sp_helpmergepublication] to public
REVOKE ALL ON [dbo].[sp_helpmergepullsubscription] to public
REVOKE ALL ON [dbo].[sp_helpmergesubscription] to public
REVOKE ALL ON [dbo].[sp_helpntgroup] to public
REVOKE ALL ON [dbo].[sp_helppublication] to public
REVOKE ALL ON [dbo].[sp_helppullsubscription] to public
REVOKE ALL ON [dbo].[sp_helpremotelogin] to public
REVOKE ALL ON [dbo].[sp_helpreplfailovermode] to public
REVOKE ALL ON [dbo].[sp_helpreplicationdb] to public
REVOKE ALL ON [dbo].[sp_helpreplicationdboption] to public
REVOKE ALL ON [dbo].[sp_helpreplicationoption] to public
REVOKE ALL ON [dbo].[sp_helprole] to public
REVOKE ALL ON [dbo].[sp_helprolemember] to public
REVOKE ALL ON [dbo].[sp_helprotect] to public
REVOKE ALL ON [dbo].[sp_helpserver] to public
REVOKE ALL ON [dbo].[sp_helpsort] to public
REVOKE ALL ON [dbo].[sp_helpsql] to public
REVOKE ALL ON [dbo].[sp_helpsrvrole] to public
REVOKE ALL ON [dbo].[sp_helpsrvrolemember] to public
REVOKE ALL ON [dbo].[sp_helpstats] to public
REVOKE ALL ON [dbo].[sp_helpsubscriberinfo] to public
REVOKE ALL ON [dbo].[sp_helpsubscription] to public
REVOKE ALL ON [dbo].[sp_helpsubscription_properties] to public
REVOKE ALL ON [dbo].[sp_helptext] to public
REVOKE ALL ON [dbo].[sp_helptrigger] to public
REVOKE ALL ON [dbo].[sp_helpuser] to public
REVOKE ALL ON [dbo].[sp_indexes] to public
REVOKE ALL ON [dbo].[sp_indexes_rowset] to public
REVOKE ALL ON [dbo].[sp_indexoption] to public
REVOKE ALL ON [dbo].[sp_invalidate_textptr] to public
REVOKE ALL ON [dbo].[sp_isarticlecolbitset] to public
REVOKE ALL ON [dbo].[sp_IsMBCSLeadByte] to public
REVOKE ALL ON [dbo].[sp_ivindexhasnullcols] to public
REVOKE ALL ON [dbo].[sp_link_publication] to public
REVOKE ALL ON [dbo].[sp_linkedservers] to public
REVOKE ALL ON [dbo].[sp_linkedservers_rowset] to public
REVOKE ALL ON [dbo].[sp_lock] to public
REVOKE ALL ON [dbo].[sp_marksubscriptionvalidation] to public
REVOKE ALL ON [dbo].[sp_mergecleanupmetadata] to public
REVOKE ALL ON [dbo].[sp_mergecompletecleanup] to public
REVOKE ALL ON [dbo].[sp_mergemetadataretentioncleanup] to public
REVOKE ALL ON [dbo].[sp_mergepreparecleanup] to public
REVOKE ALL ON [dbo].[sp_mergesubscription_cleanup] to public
REVOKE ALL ON [dbo].[sp_MS_marksystemobject] to public
REVOKE ALL ON [dbo].[sp_MS_replication_installed] to public
REVOKE ALL ON [dbo].[sp_MSacquireHeadofQueueLock] to public
REVOKE ALL ON [dbo].[sp_MSacquireserverresourcefordynamicsnapshot] to public
REVOKE ALL ON [dbo].[sp_MSacquireSlotLock] to public
REVOKE ALL ON [dbo].[sp_MSactivate_auto_sub] to public
REVOKE ALL ON [dbo].[sp_MSadd_compensating_cmd] to public
REVOKE ALL ON [dbo].[sp_MSadd_mergereplcommand] to public
REVOKE ALL ON [dbo].[sp_MSaddanonymousreplica] to public
REVOKE ALL ON [dbo].[sp_MSaddguidcolumn] to public
REVOKE ALL ON [dbo].[sp_MSaddguidindex] to public
REVOKE ALL ON [dbo].[sp_MSaddinitialarticle] to public
REVOKE ALL ON [dbo].[sp_MSaddinitialpublication] to public
REVOKE ALL ON [dbo].[sp_MSaddinitialschemaarticle] to public
REVOKE ALL ON [dbo].[sp_MSaddinitialsubscription] to public
REVOKE ALL ON [dbo].[sp_MSaddmergedynamicsnapshotjob] to public
REVOKE ALL ON [dbo].[sp_MSaddmergepub_snapshot] to public
REVOKE ALL ON [dbo].[sp_MSaddmergetriggers] to public
REVOKE ALL ON [dbo].[sp_MSaddpubtocontents] to public
REVOKE ALL ON [dbo].[sp_MSadjustmergeidentity] to public
REVOKE ALL ON [dbo].[sp_MSalreadyhavegeneration] to public
REVOKE ALL ON [dbo].[sp_MSarticlecleanup] to public
REVOKE ALL ON [dbo].[sp_MSbelongs] to public
REVOKE ALL ON [dbo].[sp_MSBumpupCompLevel] to public
REVOKE ALL ON [dbo].[sp_MSchange_priority] to public
REVOKE ALL ON [dbo].[sp_MSchange_retention] to public
REVOKE ALL ON [dbo].[sp_MSchangeobjectowner] to public
REVOKE ALL ON [dbo].[sp_MScheck_agent_instance] to public
REVOKE ALL ON [dbo].[sp_MScheck_subscription] to public
REVOKE ALL ON [dbo].[sp_MScheckatpublisher] to public
REVOKE ALL ON [dbo].[sp_MScheckexistsgeneration] to public
REVOKE ALL ON [dbo].[sp_MScheckidentityrange] to public
REVOKE ALL ON [dbo].[sp_MSCheckmergereplication] to public
REVOKE ALL ON [dbo].[sp_MScheckmetadatamatch] to public
REVOKE ALL ON [dbo].[sp_MSchecksnapshotstatus] to public
REVOKE ALL ON [dbo].[sp_MScleanup_metadata] to public
REVOKE ALL ON [dbo].[sp_MScleanup_publication_ADinfo] to public
REVOKE ALL ON [dbo].[sp_MScleanupdynsnapshotvws] to public
REVOKE ALL ON [dbo].[sp_MSCleanupForPullReinit] to public
REVOKE ALL ON [dbo].[sp_MSclearcolumnbit] to public
REVOKE ALL ON [dbo].[sp_MScomputearticlescreationorder] to public
REVOKE ALL ON [dbo].[sp_MScomputemergearticlescreationorder] to public
REVOKE ALL ON [dbo].[sp_MScomputemergeunresolvedrefs] to public
REVOKE ALL ON [dbo].[sp_MScomputeunresolvedrefs] to public
REVOKE ALL ON [dbo].[sp_MScontractsubsnb] to public
REVOKE ALL ON [dbo].[sp_MScreate_sub_tables] to public
REVOKE ALL ON [dbo].[sp_MScreateglobalreplica] to public
REVOKE ALL ON [dbo].[sp_MScreateretry] to public
REVOKE ALL ON [dbo].[sp_MSdbuseraccess] to public
REVOKE ALL ON [dbo].[sp_MSdbuserpriv] to public
REVOKE ALL ON [dbo].[sp_MSdefer_check] to public
REVOKE ALL ON [dbo].[sp_MSdeletecontents] to public
REVOKE ALL ON [dbo].[sp_MSdeletepushagent] to public
REVOKE ALL ON [dbo].[sp_MSdeleteretry] to public
REVOKE ALL ON [dbo].[sp_MSdeletetranconflictrow] to public
REVOKE ALL ON [dbo].[sp_MSdelgenzero] to public
REVOKE ALL ON [dbo].[sp_MSdelrow] to public
REVOKE ALL ON [dbo].[sp_MSdelsubrows] to public
REVOKE ALL ON [dbo].[sp_MSdelsubrowsbatch] to public
REVOKE ALL ON [dbo].[sp_MSdependencies] to public
REVOKE ALL ON [dbo].[sp_MSdroparticleconstraints] to public
REVOKE ALL ON [dbo].[sp_MSdroparticletombstones] to public
REVOKE ALL ON [dbo].[sp_MSdroparticletriggers] to public
REVOKE ALL ON [dbo].[sp_MSdropconstraints] to public
REVOKE ALL ON [dbo].[sp_MSdropdynsnapshotvws] to public
REVOKE ALL ON [dbo].[sp_MSdropfkreferencingarticle] to public
REVOKE ALL ON [dbo].[sp_MSdropmergedynamicsnapshotjob] to public
REVOKE ALL ON [dbo].[sp_MSdropmergepub_snapshot] to public
REVOKE ALL ON [dbo].[sp_MSdropretry] to public
REVOKE ALL ON [dbo].[sp_MSdroptemptable] to public
REVOKE ALL ON [dbo].[sp_MSdummyupdate] to public
REVOKE ALL ON [dbo].[sp_MSenum_replication_agents] to public
REVOKE ALL ON [dbo].[sp_MSenum_replication_job] to public
REVOKE ALL ON [dbo].[sp_MSenum_replqueues] to public
REVOKE ALL ON [dbo].[sp_MSenum_replsqlqueues] to public
REVOKE ALL ON [dbo].[sp_MSenumallpublications] to public
REVOKE ALL ON [dbo].[sp_MSenumallsubscriptions] to public
REVOKE ALL ON [dbo].[sp_MSenumchanges] to public
REVOKE ALL ON [dbo].[sp_MSenumcolumns] to public
REVOKE ALL ON [dbo].[sp_MSenumdeletesmetadata] to public
REVOKE ALL ON [dbo].[sp_MSenumgenerations] to public
REVOKE ALL ON [dbo].[sp_MSenumpartialchanges] to public
REVOKE ALL ON [dbo].[sp_MSenumpartialdeletes] to public
REVOKE ALL ON [dbo].[sp_MSenumpubreferences] to public
REVOKE ALL ON [dbo].[sp_MSenumreplicas] to public
REVOKE ALL ON [dbo].[sp_MSenumretries] to public
REVOKE ALL ON [dbo].[sp_MSenumschemachange] to public
REVOKE ALL ON [dbo].[sp_MSenumschemachange_70] to public
REVOKE ALL ON [dbo].[sp_MSenumschemachange_80] to public
REVOKE ALL ON [dbo].[sp_MSenumsubscriptions] to public
REVOKE ALL ON [dbo].[sp_MSenumthirdpartypublicationvendornames] to public
REVOKE ALL ON [dbo].[sp_MSestimatemergesnapshotworkload] to public
REVOKE ALL ON [dbo].[sp_MSestimatesnapshotworkload] to public
REVOKE ALL ON [dbo].[sp_MSevalsubscriberinfo] to public
REVOKE ALL ON [dbo].[sp_MSexclause] to public
REVOKE ALL ON [dbo].[sp_MSexpandbelongs] to public
REVOKE ALL ON [dbo].[sp_MSexpandnotbelongs] to public
REVOKE ALL ON [dbo].[sp_MSexpandsubsnb] to public
REVOKE ALL ON [dbo].[sp_MSexternalfkreferences] to public
REVOKE ALL ON [dbo].[sp_MSfetchidentityrange] to public
REVOKE ALL ON [dbo].[sp_MSfillupmissingcols] to public
REVOKE ALL ON [dbo].[sp_MSfilterclause] to public
REVOKE ALL ON [dbo].[sp_MSfixlineageversions] to public
REVOKE ALL ON [dbo].[sp_MSfixupbeforeimagetables] to public
REVOKE ALL ON [dbo].[sp_MSforeach_worker] to public
REVOKE ALL ON [dbo].[sp_MSforeachdb] to public
REVOKE ALL ON [dbo].[sp_MSforeachtable] to public
REVOKE ALL ON [dbo].[sp_MSgenreplnickname] to public
REVOKE ALL ON [dbo].[sp_MSget_agent_names] to public
REVOKE ALL ON [dbo].[sp_MSget_attach_state] to public
REVOKE ALL ON [dbo].[sp_MSget_current_activity] to public
REVOKE ALL ON [dbo].[sp_MSget_jobstate] to public
REVOKE ALL ON [dbo].[sp_MSget_load_hint] to public
REVOKE ALL ON [dbo].[sp_MSget_publisher_rpc] to public
REVOKE ALL ON [dbo].[sp_MSget_qualified_name] to public
REVOKE ALL ON [dbo].[sp_MSget_shared_agent] to public
REVOKE ALL ON [dbo].[sp_MSget_subtypedatasrc] to public
REVOKE ALL ON [dbo].[sp_MSget_synctran_commands] to public
REVOKE ALL ON [dbo].[sp_MSgetalertinfo] to public
REVOKE ALL ON [dbo].[sp_MSgetarticlereinitvalue] to public
REVOKE ALL ON [dbo].[sp_MSgetchangecount] to public
REVOKE ALL ON [dbo].[sp_MSgetcolordinalfromcolname] to public
REVOKE ALL ON [dbo].[sp_MSgetcolumnlist] to public
REVOKE ALL ON [dbo].[sp_MSgetconflictinsertproc] to public
REVOKE ALL ON [dbo].[sp_MSgetconflicttablename] to public
REVOKE ALL ON [dbo].[sp_MSgetlastrecgen] to public
REVOKE ALL ON [dbo].[sp_MSgetlastsentgen] to public
REVOKE ALL ON [dbo].[sp_MSgetlastsentrecgens] to public
REVOKE ALL ON [dbo].[sp_MSgetlastupdatedtime] to public
REVOKE ALL ON [dbo].[sp_MSgetmakegenerationapplock] to public
REVOKE ALL ON [dbo].[sp_MSgetmetadatabatch] to public
REVOKE ALL ON [dbo].[sp_MSgetonerow] to public
REVOKE ALL ON [dbo].[sp_MSgetpubinfo] to public
REVOKE ALL ON [dbo].[sp_MSgetreplicainfo] to public
REVOKE ALL ON [dbo].[sp_MSgetreplnick] to public
REVOKE ALL ON [dbo].[sp_MSgetrowmetadata] to public
REVOKE ALL ON [dbo].[sp_MSGetServerProperties] to public
REVOKE ALL ON [dbo].[sp_MSgetsubscriberinfo] to public
REVOKE ALL ON [dbo].[sp_MSgettablecontents] to public
REVOKE ALL ON [dbo].[sp_MSgettools_path] to public
REVOKE ALL ON [dbo].[sp_MSgettrancftsrcrow] to public
REVOKE ALL ON [dbo].[sp_MSgettranconflictname] to public
REVOKE ALL ON [dbo].[sp_MSgettranconflictrow] to public
REVOKE ALL ON [dbo].[sp_MSgetversion] to public
REVOKE ALL ON [dbo].[sp_MSgetviewcolumnlist] to public
REVOKE ALL ON [dbo].[sp_MShasdbaccess] to public
REVOKE ALL ON [dbo].[sp_MShelp_distdb] to public
REVOKE ALL ON [dbo].[sp_MShelp_identity_property] to public
REVOKE ALL ON [dbo].[sp_MShelp_replication_status] to public
REVOKE ALL ON [dbo].[sp_MShelp_replication_table] to public
REVOKE ALL ON [dbo].[sp_MShelpcolumns] to public
REVOKE ALL ON [dbo].[sp_MShelpconflictpublications] to public
REVOKE ALL ON [dbo].[sp_MShelpdestowner] to public
REVOKE ALL ON [dbo].[sp_MShelpfulltextindex] to public
REVOKE ALL ON [dbo].[sp_MShelpfulltextscript] to public
REVOKE ALL ON [dbo].[sp_MShelpindex] to public
REVOKE ALL ON [dbo].[sp_MShelpmergearticles] to public
REVOKE ALL ON [dbo].[sp_MShelpmergeconflictcounts] to public
REVOKE ALL ON [dbo].[sp_MShelpmergeconflictpublications] to public
REVOKE ALL ON [dbo].[sp_MShelpmergedynamicsnapshotjob] to public
REVOKE ALL ON [dbo].[sp_MShelpmergeidentity] to public
REVOKE ALL ON [dbo].[sp_MShelpmergeschemaarticles] to public
REVOKE ALL ON [dbo].[sp_MShelpobjectpublications] to public
REVOKE ALL ON [dbo].[sp_MShelptranconflictcounts] to public
REVOKE ALL ON [dbo].[sp_MShelptranconflictpublications] to public
REVOKE ALL ON [dbo].[sp_MShelptype] to public
REVOKE ALL ON [dbo].[sp_MSindexspace] to public
REVOKE ALL ON [dbo].[sp_MSinit_subscription_agent] to public
REVOKE ALL ON [dbo].[sp_MSinitdynamicsubscriber] to public
REVOKE ALL ON [dbo].[sp_MSinsertbeforeimageclause] to public
REVOKE ALL ON [dbo].[sp_MSinsertcontents] to public
REVOKE ALL ON [dbo].[sp_MSinsertdeleteconflict] to public
REVOKE ALL ON [dbo].[sp_MSinserterrorlineage] to public
REVOKE ALL ON [dbo].[sp_MSinsertgenerationschemachanges] to public
REVOKE ALL ON [dbo].[sp_MSinsertgenhistory] to public
REVOKE ALL ON [dbo].[sp_MSinsertschemachange] to public
REVOKE ALL ON [dbo].[sp_MSisnonpkukupdateinconflict] to public
REVOKE ALL ON [dbo].[sp_MSispkupdateinconflict] to public
REVOKE ALL ON [dbo].[sp_MSkilldb] to public
REVOKE ALL ON [dbo].[sp_MSlocalizeinterruptedgenerations] to public
REVOKE ALL ON [dbo].[sp_MSlocktable] to public
REVOKE ALL ON [dbo].[sp_MSloginmappings] to public
REVOKE ALL ON [dbo].[sp_MSmakearticleprocs] to public
REVOKE ALL ON [dbo].[sp_MSmakeconflictinsertproc] to public
REVOKE ALL ON [dbo].[sp_MSmakeconflicttable] to public
REVOKE ALL ON [dbo].[sp_MSmakectsview] to public
REVOKE ALL ON [dbo].[sp_MSmakedynsnapshotvws] to public
REVOKE ALL ON [dbo].[sp_MSmakegeneration] to public
REVOKE ALL ON [dbo].[sp_MSmakeinsertproc] to public
REVOKE ALL ON [dbo].[sp_MSmakeselectproc] to public
REVOKE ALL ON [dbo].[sp_MSmakesystableviews] to public
REVOKE ALL ON [dbo].[sp_MSmaketempinsertproc] to public
REVOKE ALL ON [dbo].[sp_MSmakeupdateproc] to public
REVOKE ALL ON [dbo].[sp_MSmark_proc_norepl] to public
REVOKE ALL ON [dbo].[sp_MSmarkreplinfo] to public
REVOKE ALL ON [dbo].[sp_MSmarkschemaobject] to public
REVOKE ALL ON [dbo].[sp_MSmatchkey] to public
REVOKE ALL ON [dbo].[sp_MSmergesubscribedb] to public
REVOKE ALL ON [dbo].[sp_MSmergeupdatelastsyncinfo] to public
REVOKE ALL ON [dbo].[sp_MSobjectprivs] to public
REVOKE ALL ON [dbo].[sp_MSobjsearch] to public
REVOKE ALL ON [dbo].[sp_MSpost_auto_proc] to public
REVOKE ALL ON [dbo].[sp_MSprep_exclusive] to public
REVOKE ALL ON [dbo].[sp_MSprepare_mergearticle] to public
REVOKE ALL ON [dbo].[sp_MSpreparecleanup] to public
REVOKE ALL ON [dbo].[sp_MSproxiedmetadata] to public
REVOKE ALL ON [dbo].[sp_MSpub_adjust_identity] to public
REVOKE ALL ON [dbo].[sp_MSpublicationcleanup] to public
REVOKE ALL ON [dbo].[sp_MSpublicationview] to public
REVOKE ALL ON [dbo].[sp_MSpurgecontentsorphans] to public
REVOKE ALL ON [dbo].[sp_MSquerysubtype] to public
REVOKE ALL ON [dbo].[sp_MSquiescecheck] to public
REVOKE ALL ON [dbo].[sp_MSquiesceforcleanup] to public
REVOKE ALL ON [dbo].[sp_MSquiescetriggerson] to public
REVOKE ALL ON [dbo].[sp_MSreenable_check] to public
REVOKE ALL ON [dbo].[sp_MSreinit_hub] to public
REVOKE ALL ON [dbo].[sp_MSreinitmergepublication] to public
REVOKE ALL ON [dbo].[sp_MSreleasemakegenerationapplock] to public
REVOKE ALL ON [dbo].[sp_MSreleaseSlotLock] to public
REVOKE ALL ON [dbo].[sp_MSremove_mergereplcommand] to public
REVOKE ALL ON [dbo].[sp_MSremove_userscript] to public
REVOKE ALL ON [dbo].[sp_MSrepl_check_server] to public
REVOKE ALL ON [dbo].[sp_MSrepl_gettype_mappings] to public
REVOKE ALL ON [dbo].[sp_MSrepl_isdbowner] to public
REVOKE ALL ON [dbo].[sp_MSrepl_linkedservers_rowset] to public
REVOKE ALL ON [dbo].[sp_MSrepl_schema] to public
REVOKE ALL ON [dbo].[sp_MSreplcheck_connection] to public
REVOKE ALL ON [dbo].[sp_MSreplcheck_permission] to public
REVOKE ALL ON [dbo].[sp_MSreplcheck_pull] to public
REVOKE ALL ON [dbo].[sp_MSreplcheck_qv] to public
REVOKE ALL ON [dbo].[sp_MSreplcheck_subscribe] to public
REVOKE ALL ON [dbo].[sp_MSreplraiserror] to public
REVOKE ALL ON [dbo].[sp_MSreplupdateschema] to public
REVOKE ALL ON [dbo].[sp_MSreset_attach_state] to public
REVOKE ALL ON [dbo].[sp_MSreset_queue] to public
REVOKE ALL ON [dbo].[sp_MSreset_queued_reinit] to public
REVOKE ALL ON [dbo].[sp_MSreset_synctran_bit] to public
REVOKE ALL ON [dbo].[sp_MSretrieve_publication_attributes] to public
REVOKE ALL ON [dbo].[sp_MSscript_article_view] to public
REVOKE ALL ON [dbo].[sp_MSscript_beginproc] to public
REVOKE ALL ON [dbo].[sp_MSscript_begintrig1] to public
REVOKE ALL ON [dbo].[sp_MSscript_begintrig2] to public
REVOKE ALL ON [dbo].[sp_MSscript_compensating_send] to public
REVOKE ALL ON [dbo].[sp_MSscript_delete_statement] to public
REVOKE ALL ON [dbo].[sp_MSscript_dri] to public
REVOKE ALL ON [dbo].[sp_MSscript_endproc] to public
REVOKE ALL ON [dbo].[sp_MSscript_endtrig] to public
REVOKE ALL ON [dbo].[sp_MSscript_ExecutionMode_stmt] to public
REVOKE ALL ON [dbo].[sp_MSscript_insert_statement] to public
REVOKE ALL ON [dbo].[sp_MSscript_multirow_trigger] to public
REVOKE ALL ON [dbo].[sp_MSscript_params] to public
REVOKE ALL ON [dbo].[sp_MSscript_pkvar_assignment] to public
REVOKE ALL ON [dbo].[sp_MSscript_procbodystart] to public
REVOKE ALL ON [dbo].[sp_MSscript_pub_upd_trig] to public
REVOKE ALL ON [dbo].[sp_MSscript_security] to public
REVOKE ALL ON [dbo].[sp_MSscript_singlerow_trigger] to public
REVOKE ALL ON [dbo].[sp_MSscript_sync_del_proc] to public
REVOKE ALL ON [dbo].[sp_MSscript_sync_del_trig] to public
REVOKE ALL ON [dbo].[sp_MSscript_sync_ins_proc] to public
REVOKE ALL ON [dbo].[sp_MSscript_sync_ins_trig] to public
REVOKE ALL ON [dbo].[sp_MSscript_sync_upd_proc] to public
REVOKE ALL ON [dbo].[sp_MSscript_sync_upd_trig] to public
REVOKE ALL ON [dbo].[sp_MSscript_trigger_assignment] to public
REVOKE ALL ON [dbo].[sp_MSscript_trigger_exec_rpc] to public
REVOKE ALL ON [dbo].[sp_MSscript_trigger_fetch_statement] to public
REVOKE ALL ON [dbo].[sp_MSscript_trigger_update_checks] to public
REVOKE ALL ON [dbo].[sp_MSscript_trigger_updates] to public
REVOKE ALL ON [dbo].[sp_MSscript_trigger_variables] to public
REVOKE ALL ON [dbo].[sp_MSscriptdatabase] to public
REVOKE ALL ON [dbo].[sp_MSscriptdb_worker] to public
REVOKE ALL ON [dbo].[sp_MSscriptmvastable] to public
REVOKE ALL ON [dbo].[sp_MSscriptmvastableidx] to public
REVOKE ALL ON [dbo].[sp_MSscriptmvastablenci] to public
REVOKE ALL ON [dbo].[sp_MSscriptmvastablepkc] to public
REVOKE ALL ON [dbo].[sp_MSscriptviewproc] to public
REVOKE ALL ON [dbo].[sp_MSsendtosqlqueue] to public
REVOKE ALL ON [dbo].[sp_MSset_current_activity] to public
REVOKE ALL ON [dbo].[sp_MSset_sub_guid] to public
REVOKE ALL ON [dbo].[sp_MSset_subscription_properties] to public
REVOKE ALL ON [dbo].[sp_MSsetaccesslist] to public
REVOKE ALL ON [dbo].[sp_MSsetalertinfo] to public
REVOKE ALL ON [dbo].[sp_MSsetartprocs] to public
REVOKE ALL ON [dbo].[sp_MSsetbit] to public
REVOKE ALL ON [dbo].[sp_MSsetconflictscript] to public
REVOKE ALL ON [dbo].[sp_MSsetconflicttable] to public
REVOKE ALL ON [dbo].[sp_MSsetcontext_replagent] to public
REVOKE ALL ON [dbo].[sp_MSsethighestversion] to public
REVOKE ALL ON [dbo].[sp_MSsetlastrecgen] to public
REVOKE ALL ON [dbo].[sp_MSsetlastsentgen] to public
REVOKE ALL ON [dbo].[sp_MSsetreplicainfo] to public
REVOKE ALL ON [dbo].[sp_MSsetreplicastatus] to public
REVOKE ALL ON [dbo].[sp_MSsetrowmetadata] to public
REVOKE ALL ON [dbo].[sp_MSSetServerProperties] to public
REVOKE ALL ON [dbo].[sp_MSsetsubscriberinfo] to public
REVOKE ALL ON [dbo].[sp_MSsettopology] to public
REVOKE ALL ON [dbo].[sp_MSsetupbelongs] to public
REVOKE ALL ON [dbo].[sp_MSsetupbelongs_withoutviewproc] to public
REVOKE ALL ON [dbo].[sp_MSsetupnotbelongs] to public
REVOKE ALL ON [dbo].[sp_MSsetupworktables] to public
REVOKE ALL ON [dbo].[sp_MSSharedFixedDisk] to public
REVOKE ALL ON [dbo].[sp_MSSQLDMO70_version] to public
REVOKE ALL ON [dbo].[sp_MSSQLDMO80_version] to public
REVOKE ALL ON [dbo].[sp_MSSQLOLE_version] to public
REVOKE ALL ON [dbo].[sp_MSSQLOLE65_version] to public
REVOKE ALL ON [dbo].[sp_MSsub_check_identity] to public
REVOKE ALL ON [dbo].[sp_MSsub_set_identity] to public
REVOKE ALL ON [dbo].[sp_MSsubscriptionvalidated] to public
REVOKE ALL ON [dbo].[sp_MStablechecks] to public
REVOKE ALL ON [dbo].[sp_MStablekeys] to public
REVOKE ALL ON [dbo].[sp_MStablerefs] to public
REVOKE ALL ON [dbo].[sp_MStablespace] to public
REVOKE ALL ON [dbo].[sp_MStestbit] to public
REVOKE ALL ON [dbo].[sp_MSuniquename] to public
REVOKE ALL ON [dbo].[sp_MSunmarkifneeded] to public
REVOKE ALL ON [dbo].[sp_MSunmarkreplinfo] to public
REVOKE ALL ON [dbo].[sp_MSunmarkschemaobject] to public
REVOKE ALL ON [dbo].[sp_MSupdate_mqserver_subdb] to public
REVOKE ALL ON [dbo].[sp_MSupdatecontents] to public
REVOKE ALL ON [dbo].[sp_MSupdategenhistory] to public
REVOKE ALL ON [dbo].[sp_MSupdatelastsyncinfo] to public
REVOKE ALL ON [dbo].[sp_MSupdateschemachange] to public
REVOKE ALL ON [dbo].[sp_MSupdatesysmergearticles] to public
REVOKE ALL ON [dbo].[sp_msupg_createcatalogcomputedcols] to public
REVOKE ALL ON [dbo].[sp_msupg_dosystabcatalogupgrades] to public
REVOKE ALL ON [dbo].[sp_msupg_dropcatalogcomputedcols] to public
REVOKE ALL ON [dbo].[sp_msupg_recreatecatalogfaketables] to public
REVOKE ALL ON [dbo].[sp_msupg_recreatesystemviews] to public
REVOKE ALL ON [dbo].[sp_msupg_removesystemcomputedcolumns] to public
REVOKE ALL ON [dbo].[sp_msupg_upgradecatalog] to public
REVOKE ALL ON [dbo].[sp_MSuplineageversion] to public
REVOKE ALL ON [dbo].[sp_MSvalidate_subscription] to public
REVOKE ALL ON [dbo].[sp_MSvalidatearticle] to public
REVOKE ALL ON [dbo].[sp_objectfilegroup] to public
REVOKE ALL ON [dbo].[sp_oledb_column_constraints] to public
REVOKE ALL ON [dbo].[sp_oledb_database] to public
REVOKE ALL ON [dbo].[sp_oledb_defdb] to public
REVOKE ALL ON [dbo].[sp_oledb_deflang] to public
REVOKE ALL ON [dbo].[sp_oledb_indexinfo] to public
REVOKE ALL ON [dbo].[sp_oledb_language] to public
REVOKE ALL ON [dbo].[sp_oledb_ro_usrname] to public
REVOKE ALL ON [dbo].[sp_password] to public
REVOKE ALL ON [dbo].[sp_pkeys] to public
REVOKE ALL ON [dbo].[sp_prepare] to public
REVOKE ALL ON [dbo].[sp_prepexec] to public
REVOKE ALL ON [dbo].[sp_prepexecrpc] to public
REVOKE ALL ON [dbo].[sp_primary_keys_rowset] to public
REVOKE ALL ON [dbo].[sp_primarykeys] to public
REVOKE ALL ON [dbo].[sp_procedure_params_rowset] to public
REVOKE ALL ON [dbo].[sp_procedures_rowset] to public
REVOKE ALL ON [dbo].[sp_procoption] to public
REVOKE ALL ON [dbo].[sp_prop_oledb_provider] to public
REVOKE ALL ON [dbo].[sp_provider_types_rowset] to public
REVOKE ALL ON [dbo].[sp_publication_validation] to public
REVOKE ALL ON [dbo].[sp_readerrorlog] to public
REVOKE ALL ON [dbo].[sp_readwebtask] to public
REVOKE ALL ON [dbo].[sp_recompile] to public
REVOKE ALL ON [dbo].[sp_refreshsubscriptions] to public
REVOKE ALL ON [dbo].[sp_refreshview] to public
REVOKE ALL ON [dbo].[sp_reinitmergepullsubscription] to public
REVOKE ALL ON [dbo].[sp_reinitmergesubscription] to public
REVOKE ALL ON [dbo].[sp_reinitpullsubscription] to public
REVOKE ALL ON [dbo].[sp_reinitsubscription] to public
REVOKE ALL ON [dbo].[sp_releaseapplock] to public
REVOKE ALL ON [dbo].[sp_releaseschemalock] to public
REVOKE ALL ON [dbo].[sp_remoteoption] to public
REVOKE ALL ON [dbo].[sp_rename] to public
REVOKE ALL ON [dbo].[sp_renamedb] to public
REVOKE ALL ON [dbo].[sp_replcmds] to public
REVOKE ALL ON [dbo].[sp_replcounters] to public
REVOKE ALL ON [dbo].[sp_repldeletequeuedtran] to public
REVOKE ALL ON [dbo].[sp_repldone] to public
REVOKE ALL ON [dbo].[sp_replica] to public
REVOKE ALL ON [dbo].[sp_replicationoption] to public
REVOKE ALL ON [dbo].[sp_replincrementlsn] to public
REVOKE ALL ON [dbo].[sp_replpostschema] to public
REVOKE ALL ON [dbo].[sp_replpostsyncstatus] to public
REVOKE ALL ON [dbo].[sp_replproberemoteserver] to public
REVOKE ALL ON [dbo].[sp_replrestart] to public
REVOKE ALL ON [dbo].[sp_replsendtoqueue] to public
REVOKE ALL ON [dbo].[sp_replsetoriginator] to public
REVOKE ALL ON [dbo].[sp_replsetsyncstatus] to public
REVOKE ALL ON [dbo].[sp_replsqlqgetrows] to public
REVOKE ALL ON [dbo].[sp_repltrans] to public
REVOKE ALL ON [dbo].[sp_replwritetovarbin] to public
REVOKE ALL ON [dbo].[sp_reset_connection] to public
REVOKE ALL ON [dbo].[sp_resyncexecute] to public
REVOKE ALL ON [dbo].[sp_resyncexecutesql] to public
REVOKE ALL ON [dbo].[sp_resyncmergesubscription] to public
REVOKE ALL ON [dbo].[sp_resyncprepare] to public
REVOKE ALL ON [dbo].[sp_resyncuniquetable] to public
REVOKE ALL ON [dbo].[sp_revoke_publication_access] to public
REVOKE ALL ON [dbo].[sp_revokedbaccess] to public
REVOKE ALL ON [dbo].[sp_revokelogin] to public
REVOKE ALL ON [dbo].[sp_runwebtask] to public
REVOKE ALL ON [dbo].[sp_schemata_rowset] to public
REVOKE ALL ON [dbo].[sp_script_reconciliation_delproc] to public
REVOKE ALL ON [dbo].[sp_script_reconciliation_insproc] to public
REVOKE ALL ON [dbo].[sp_script_reconciliation_xdelproc] to public
REVOKE ALL ON [dbo].[sp_script_synctran_commands] to public
REVOKE ALL ON [dbo].[sp_scriptdelproc] to public
REVOKE ALL ON [dbo].[sp_scriptdynamicupdproc] to public
REVOKE ALL ON [dbo].[sp_scriptinsproc] to public
REVOKE ALL ON [dbo].[sp_scriptmappedupdproc] to public
REVOKE ALL ON [dbo].[sp_scriptpkwhereclause] to public
REVOKE ALL ON [dbo].[sp_scriptpublicationcustomprocs] to public
REVOKE ALL ON [dbo].[sp_scriptreconwhereclause] to public
REVOKE ALL ON [dbo].[sp_scriptsubconflicttable] to public
REVOKE ALL ON [dbo].[sp_scriptupdateparams] to public
REVOKE ALL ON [dbo].[sp_scriptupdproc] to public
REVOKE ALL ON [dbo].[sp_scriptxdelproc] to public
REVOKE ALL ON [dbo].[sp_scriptxupdproc] to public
REVOKE ALL ON [dbo].[sp_server_info] to public
REVOKE ALL ON [dbo].[sp_serveroption] to public
REVOKE ALL ON [dbo].[sp_setapprole] to public
REVOKE ALL ON [dbo].[sp_setnetname] to public
REVOKE ALL ON [dbo].[sp_setreplfailovermode] to public
REVOKE ALL ON [dbo].[sp_settriggerorder] to public
REVOKE ALL ON [dbo].[sp_showrowreplicainfo] to public
REVOKE ALL ON [dbo].[sp_spaceused] to public
REVOKE ALL ON [dbo].[sp_special_columns] to public
REVOKE ALL ON [dbo].[sp_sproc_columns] to public
REVOKE ALL ON [dbo].[sp_sqlexec] to public
REVOKE ALL ON [dbo].[sp_srvrolepermission] to public
REVOKE ALL ON [dbo].[sp_statistics] to public
REVOKE ALL ON [dbo].[sp_statistics_rowset] to public
REVOKE ALL ON [dbo].[sp_stored_procedures] to public
REVOKE ALL ON [dbo].[sp_subscribe] to public
REVOKE ALL ON [dbo].[sp_table_constraints_rowset] to public
REVOKE ALL ON [dbo].[sp_table_privileges] to public
REVOKE ALL ON [dbo].[sp_table_privileges_ex] to public
REVOKE ALL ON [dbo].[sp_table_privileges_rowset] to public
REVOKE ALL ON [dbo].[sp_table_statistics_rowset] to public
REVOKE ALL ON [dbo].[sp_table_validation] to public
REVOKE ALL ON [dbo].[sp_tablecollations] to public
REVOKE ALL ON [dbo].[sp_tableoption] to public
REVOKE ALL ON [dbo].[sp_tables] to public
REVOKE ALL ON [dbo].[sp_tables_ex] to public
REVOKE ALL ON [dbo].[sp_tables_info_rowset] to public
REVOKE ALL ON [dbo].[sp_tables_rowset] to public
REVOKE ALL ON [dbo].[sp_tableswc] to public
REVOKE ALL ON [dbo].[sp_tempdbspace] to public
REVOKE ALL ON [dbo].[sp_unbindefault] to public
REVOKE ALL ON [dbo].[sp_unbindrule] to public
REVOKE ALL ON [dbo].[sp_unprepare] to public
REVOKE ALL ON [dbo].[sp_unsubscribe] to public
REVOKE ALL ON [dbo].[sp_updateextendedproperty] to public
REVOKE ALL ON [dbo].[sp_updatestats] to public
REVOKE ALL ON [dbo].[sp_user_counter1] to public
REVOKE ALL ON [dbo].[sp_user_counter10] to public
REVOKE ALL ON [dbo].[sp_user_counter2] to public
REVOKE ALL ON [dbo].[sp_user_counter3] to public
REVOKE ALL ON [dbo].[sp_user_counter4] to public
REVOKE ALL ON [dbo].[sp_user_counter5] to public
REVOKE ALL ON [dbo].[sp_user_counter6] to public
REVOKE ALL ON [dbo].[sp_user_counter7] to public
REVOKE ALL ON [dbo].[sp_user_counter8] to public
REVOKE ALL ON [dbo].[sp_user_counter9] to public
REVOKE ALL ON [dbo].[sp_validatelogins] to public
REVOKE ALL ON [dbo].[sp_validatemergepublication] to public
REVOKE ALL ON [dbo].[sp_validatemergepullsubscription] to public
REVOKE ALL ON [dbo].[sp_validatemergesubscription] to public
REVOKE ALL ON [dbo].[sp_validlang] to public
REVOKE ALL ON [dbo].[sp_validname] to public
REVOKE ALL ON [dbo].[sp_verify_publication] to public
REVOKE ALL ON [dbo].[sp_who] to public
REVOKE ALL ON [dbo].[sp_who2] to public
REVOKE ALL ON [dbo].[sp_xml_preparedocument] to public
REVOKE ALL ON [dbo].[sp_xml_removedocument] to public
REVOKE ALL ON [dbo].[spt_datatype_info] to public
REVOKE ALL ON [dbo].[spt_datatype_info_ext] to public
REVOKE ALL ON [dbo].[spt_fallback_db] to public
REVOKE ALL ON [dbo].[spt_fallback_dev] to public
REVOKE ALL ON [dbo].[spt_fallback_usg] to public
REVOKE ALL ON [dbo].[spt_monitor] to public
REVOKE ALL ON [dbo].[spt_provider_types] to public
REVOKE ALL ON [dbo].[spt_server_info] to public
REVOKE ALL ON [dbo].[spt_values] to public
REVOKE ALL ON [dbo].[syscharsets] to public
REVOKE ALL ON [dbo].[syscolumns] to public
REVOKE ALL ON [dbo].[syscomments] to public
REVOKE ALL ON [dbo].[sysconfigures] to public
REVOKE ALL ON [dbo].[sysconstraints] to public
REVOKE ALL ON [dbo].[syscurconfigs] to public
REVOKE ALL ON [dbo].[sysdatabases] to public
REVOKE ALL ON [dbo].[sysdepends] to public
REVOKE ALL ON [dbo].[sysdevices] to public
REVOKE ALL ON [dbo].[sysfilegroups] to public
REVOKE ALL ON [dbo].[sysfiles] to public
REVOKE ALL ON [dbo].[sysforeignkeys] to public
REVOKE ALL ON [dbo].[sysfulltextcatalogs] to public
REVOKE ALL ON [dbo].[sysindexes] to public
REVOKE ALL ON [dbo].[sysindexkeys] to public
REVOKE ALL ON [dbo].[syslanguages] to public
REVOKE ALL ON [dbo].[syslockinfo] to public
REVOKE ALL ON [dbo].[syslocks] to public
REVOKE ALL ON [dbo].[syslogins] to public
REVOKE ALL ON [dbo].[sysmembers] to public
REVOKE ALL ON [dbo].[sysmessages] to public
REVOKE ALL ON [dbo].[sysobjects] to public
REVOKE ALL ON [dbo].[sysoledbusers] to public
REVOKE ALL ON [dbo].[sysopentapes] to public
REVOKE ALL ON [dbo].[syspermissions] to public
REVOKE ALL ON [dbo].[sysprocesses] to public
REVOKE ALL ON [dbo].[sysprotects] to public
REVOKE ALL ON [dbo].[sysreferences] to public
REVOKE ALL ON [dbo].[sysremotelogins] to public
REVOKE ALL ON [dbo].[syssegments] to public
REVOKE ALL ON [dbo].[sysservers] to public
REVOKE ALL ON [dbo].[systypes] to public
REVOKE ALL ON [dbo].[sysusers] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[TABLE_PRIVILEGES] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[TABLES] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[VIEW_COLUMN_USAGE] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[VIEW_TABLE_USAGE] to public
REVOKE ALL ON [INFORMATION_SCHEMA].[VIEWS] to public
REVOKE ALL ON [dbo].[xp_dirtree] to public
REVOKE ALL ON [dbo].[xp_enum_activescriptengines] to public
REVOKE ALL ON [dbo].[xp_fileexist] to public
REVOKE ALL ON [dbo].[xp_fixeddrives] to public
REVOKE ALL ON [dbo].[xp_GetAdminGroupName] to public
REVOKE ALL ON [dbo].[xp_getfiledetails] to public
REVOKE ALL ON [dbo].[xp_getnetname] to public
REVOKE ALL ON [dbo].[xp_grantlogin] to public
REVOKE ALL ON [dbo].[xp_instance_regread] to public
REVOKE ALL ON [dbo].[xp_IsNTAdmin] to public
REVOKE ALL ON [dbo].[xp_mapdown_bitmap] to public
REVOKE ALL ON [dbo].[xp_mergelineages] to public
REVOKE ALL ON [dbo].[xp_mergexpusage] to public
REVOKE ALL ON [dbo].[xp_MSADEnabled] to public
REVOKE ALL ON [dbo].[xp_MSFullText] to public
REVOKE ALL ON [dbo].[xp_MSLocalSystem] to public
REVOKE ALL ON [dbo].[xp_MSnt2000] to public
REVOKE ALL ON [dbo].[xp_MSplatform] to public
REVOKE ALL ON [dbo].[xp_msver] to public
REVOKE ALL ON [dbo].[xp_ntsec_enumdomains] to public
REVOKE ALL ON [dbo].[xp_ORbitmap] to public
REVOKE ALL ON [dbo].[xp_peekqueue] to public
REVOKE ALL ON [dbo].[xp_proxiedmetadata] to public
REVOKE ALL ON [dbo].[xp_qv] to public
REVOKE ALL ON [dbo].[xp_regread] to public
REVOKE ALL ON [dbo].[xp_revokelogin] to public
REVOKE ALL ON [dbo].[xp_showcolv] to public
REVOKE ALL ON [dbo].[xp_showlineage] to public
REVOKE ALL ON [dbo].[xp_sprintf] to public
REVOKE ALL ON [dbo].[xp_sscanf] to public
REVOKE ALL ON [dbo].[xp_unc_to_drive] to public
REVOKE ALL ON [dbo].[xp_varbintohexstr] to public
GO
------------------------------------------------------------------------------
-- model: Clear PUBLIC permissions on database.
USE model
GO
REVOKE ALL ON [dbo].[syscolumns] to public
REVOKE ALL ON [dbo].[syscomments] to public
REVOKE ALL ON [dbo].[sysconstraints] to public
REVOKE ALL ON [dbo].[sysdepends] to public
REVOKE ALL ON [dbo].[sysfilegroups] to public
REVOKE ALL ON [dbo].[sysfiles] to public
REVOKE ALL ON [dbo].[sysforeignkeys] to public
REVOKE ALL ON [dbo].[sysfulltextcatalogs] to public
REVOKE ALL ON [dbo].[sysindexes] to public
REVOKE ALL ON [dbo].[sysindexkeys] to public
REVOKE ALL ON [dbo].[sysmembers] to public
REVOKE ALL ON [dbo].[sysobjects] to public
REVOKE ALL ON [dbo].[syspermissions] to public
REVOKE ALL ON [dbo].[sysprotects] to public
REVOKE ALL ON [dbo].[sysreferences] to public
REVOKE ALL ON [dbo].[syssegments] to public
REVOKE ALL ON [dbo].[systypes] to public
REVOKE ALL ON [dbo].[sysusers] to public
GO
------------------------------------------------------------------------------
-- msdb: Clear PUBLIC permissions on database.
USE msdb
GO
REVOKE ALL ON [dbo].[backupfile] to public
REVOKE ALL ON [dbo].[backupmediafamily] to public
REVOKE ALL ON [dbo].[backupmediaset] to public
REVOKE ALL ON [dbo].[backupset] to public
REVOKE ALL ON [dbo].[logmarkhistory] to public
REVOKE ALL ON [dbo].[mswebtasks] to public
REVOKE ALL ON [dbo].[r_iRTblClassDefs] to public
REVOKE ALL ON [dbo].[r_iRTblDBMProps] to public
REVOKE ALL ON [dbo].[r_iRTblDBXProps] to public
REVOKE ALL ON [dbo].[r_iRTblDTMProps] to public
REVOKE ALL ON [dbo].[r_iRTblDTSProps] to public
REVOKE ALL ON [dbo].[r_iRTblEnumerationDef] to public
REVOKE ALL ON [dbo].[r_iRTblEnumerationValueDef] to public
REVOKE ALL ON [dbo].[r_iRTblEQMProps] to public
REVOKE ALL ON [dbo].[r_iRTblGENProps] to public
REVOKE ALL ON [dbo].[r_iRTblIfaceDefs] to public
REVOKE ALL ON [dbo].[r_iRTblIfaceMem] to public
REVOKE ALL ON [dbo].[r_iRTblMDSProps] to public
REVOKE ALL ON [dbo].[r_iRTblNamedObj] to public
REVOKE ALL ON [dbo].[r_iRTblOLPProps] to public
REVOKE ALL ON [dbo].[r_iRTblParameterDef] to public
REVOKE ALL ON [dbo].[r_iRTblPropDefs] to public
REVOKE ALL ON [dbo].[r_iRTblProps] to public
REVOKE ALL ON [dbo].[r_iRTblRelColDefs] to public
REVOKE ALL ON [dbo].[r_iRTblRelshipDefs] to public
REVOKE ALL ON [dbo].[r_iRTblRelshipProps] to public
REVOKE ALL ON [dbo].[r_iRTblRelships] to public
REVOKE ALL ON [dbo].[r_iRTblScriptDefs] to public
REVOKE ALL ON [dbo].[r_iRTblSIMProps] to public
REVOKE ALL ON [dbo].[r_iRTblSites] to public
REVOKE ALL ON [dbo].[r_iRTblSumInfo] to public
REVOKE ALL ON [dbo].[r_iRTblTFMProps] to public
REVOKE ALL ON [dbo].[r_iRTblTypeInfo] to public
REVOKE ALL ON [dbo].[r_iRTblTypeLibs] to public
REVOKE ALL ON [dbo].[r_iRTblUMLProps] to public
REVOKE ALL ON [dbo].[r_iRTblUMXProps] to public
REVOKE ALL ON [dbo].[r_iRTblVersionAdminInfo] to public
REVOKE ALL ON [dbo].[r_iRTblVersions] to public
REVOKE ALL ON [dbo].[r_iRTblWorkspaceItems] to public
REVOKE ALL ON [dbo].[restorefile] to public
REVOKE ALL ON [dbo].[restorefilegroup] to public
REVOKE ALL ON [dbo].[restorehistory] to public
REVOKE ALL ON [dbo].[RTblClassDefs] to public
REVOKE ALL ON [dbo].[RTblDatabaseVersion] to public
REVOKE ALL ON [dbo].[RTblDBMProps] to public
REVOKE ALL ON [dbo].[RTblDBXProps] to public
REVOKE ALL ON [dbo].[RTblDTMProps] to public
REVOKE ALL ON [dbo].[RTblDTSProps] to public
REVOKE ALL ON [dbo].[RTblEnumerationDef] to public
REVOKE ALL ON [dbo].[RTblEnumerationValueDef] to public
REVOKE ALL ON [dbo].[RTblEQMProps] to public
REVOKE ALL ON [dbo].[RTblGENProps] to public
REVOKE ALL ON [dbo].[RTblIfaceDefs] to public
REVOKE ALL ON [dbo].[RTblIfaceHier] to public
REVOKE ALL ON [dbo].[RTblIfaceMem] to public
REVOKE ALL ON [dbo].[RTblMDSProps] to public
REVOKE ALL ON [dbo].[RTblNamedObj] to public
REVOKE ALL ON [dbo].[RTblOLPProps] to public
REVOKE ALL ON [dbo].[RTblParameterDef] to public
REVOKE ALL ON [dbo].[RTblPropDefs] to public
REVOKE ALL ON [dbo].[RTblProps] to public
REVOKE ALL ON [dbo].[RTblRelColDefs] to public
REVOKE ALL ON [dbo].[RTblRelshipDefs] to public
REVOKE ALL ON [dbo].[RTblRelshipProps] to public
REVOKE ALL ON [dbo].[RTblRelships] to public
REVOKE ALL ON [dbo].[RTblScriptDefs] to public
REVOKE ALL ON [dbo].[RTblSIMProps] to public
REVOKE ALL ON [dbo].[RTblSites] to public
REVOKE ALL ON [dbo].[RTblSumInfo] to public
REVOKE ALL ON [dbo].[RTblTFMProps] to public
REVOKE ALL ON [dbo].[RTblTypeInfo] to public
REVOKE ALL ON [dbo].[RTblTypeLibs] to public
REVOKE ALL ON [dbo].[RTblUMLProps] to public
REVOKE ALL ON [dbo].[RTblUMXProps] to public
REVOKE ALL ON [dbo].[RTblVersionAdminInfo] to public
REVOKE ALL ON [dbo].[RTblVersions] to public
REVOKE ALL ON [dbo].[RTblWorkspaceItems] to public
REVOKE ALL ON [dbo].[sp_add_dtspackage] to public
REVOKE ALL ON [dbo].[sp_add_job] to public
REVOKE ALL ON [dbo].[sp_add_jobschedule] to public
REVOKE ALL ON [dbo].[sp_add_jobserver] to public
REVOKE ALL ON [dbo].[sp_add_jobstep] to public
REVOKE ALL ON [dbo].[sp_addtask] to public
REVOKE ALL ON [dbo].[sp_check_for_owned_jobs] to public
REVOKE ALL ON [dbo].[sp_check_for_owned_jobsteps] to public
REVOKE ALL ON [dbo].[sp_delete_job] to public
REVOKE ALL ON [dbo].[sp_delete_jobschedule] to public
REVOKE ALL ON [dbo].[sp_delete_jobserver] to public
REVOKE ALL ON [dbo].[sp_delete_jobstep] to public
REVOKE ALL ON [dbo].[sp_drop_dtspackage] to public
REVOKE ALL ON [dbo].[sp_droptask] to public
REVOKE ALL ON [dbo].[sp_dump_dtslog_all] to public
REVOKE ALL ON [dbo].[sp_dump_dtspackagelog] to public
REVOKE ALL ON [dbo].[sp_dump_dtssteplog] to public
REVOKE ALL ON [dbo].[sp_dump_dtstasklog] to public
REVOKE ALL ON [dbo].[sp_enum_dtspackagelog] to public
REVOKE ALL ON [dbo].[sp_enum_dtspackages] to public
REVOKE ALL ON [dbo].[sp_enum_dtssteplog] to public
REVOKE ALL ON [dbo].[sp_enum_dtstasklog] to public
REVOKE ALL ON [dbo].[sp_enum_sqlagent_subsystems] to public
REVOKE ALL ON [dbo].[sp_get_dtspackage] to public
REVOKE ALL ON [dbo].[sp_get_dtsversion] to public
REVOKE ALL ON [dbo].[sp_get_job_alerts] to public
REVOKE ALL ON [dbo].[sp_get_jobstep_db_username] to public
REVOKE ALL ON [dbo].[sp_get_log_shipping_monitor_info] to public
REVOKE ALL ON [dbo].[sp_get_sqlagent_properties] to public
REVOKE ALL ON [dbo].[sp_help_category] to public
REVOKE ALL ON [dbo].[sp_help_job] to public
REVOKE ALL ON [dbo].[sp_help_jobhistory] to public
REVOKE ALL ON [dbo].[sp_help_jobschedule] to public
REVOKE ALL ON [dbo].[sp_help_jobserver] to public
REVOKE ALL ON [dbo].[sp_help_jobstep] to public
REVOKE ALL ON [dbo].[sp_helphistory] to public
REVOKE ALL ON [dbo].[sp_helptask] to public
REVOKE ALL ON [dbo].[sp_log_dtspackage_begin] to public
REVOKE ALL ON [dbo].[sp_log_dtspackage_end] to public
REVOKE ALL ON [dbo].[sp_log_dtsstep_begin] to public
REVOKE ALL ON [dbo].[sp_log_dtsstep_end] to public
REVOKE ALL ON [dbo].[sp_log_dtstask] to public
REVOKE ALL ON [dbo].[sp_make_dtspackagename] to public
REVOKE ALL ON [dbo].[sp_post_msx_operation] to public
REVOKE ALL ON [dbo].[sp_purge_jobhistory] to public
REVOKE ALL ON [dbo].[sp_purgehistory] to public
REVOKE ALL ON [dbo].[sp_reassign_dtspackageowner] to public
REVOKE ALL ON [dbo].[sp_reassigntask] to public
REVOKE ALL ON [dbo].[sp_start_job] to public
REVOKE ALL ON [dbo].[sp_stop_job] to public
REVOKE ALL ON [dbo].[sp_uniquetaskname] to public
REVOKE ALL ON [dbo].[sp_update_job] to public
REVOKE ALL ON [dbo].[sp_update_jobschedule] to public
REVOKE ALL ON [dbo].[sp_update_jobstep] to public
REVOKE ALL ON [dbo].[sp_updatetask] to public
REVOKE ALL ON [dbo].[sp_verifytaskid] to public
REVOKE ALL ON [dbo].[syscategories] to public
REVOKE ALL ON [dbo].[syscolumns] to public
REVOKE ALL ON [dbo].[syscomments] to public
REVOKE ALL ON [dbo].[sysconstraints] to public
REVOKE ALL ON [dbo].[sysdepends] to public
REVOKE ALL ON [dbo].[sysfilegroups] to public
REVOKE ALL ON [dbo].[sysfiles] to public
REVOKE ALL ON [dbo].[sysforeignkeys] to public
REVOKE ALL ON [dbo].[sysfulltextcatalogs] to public
REVOKE ALL ON [dbo].[sysindexes] to public
REVOKE ALL ON [dbo].[sysindexkeys] to public
REVOKE ALL ON [dbo].[sysjobs_view] to public
REVOKE ALL ON [dbo].[sysmembers] to public
REVOKE ALL ON [dbo].[sysobjects] to public
REVOKE ALL ON [dbo].[syspermissions] to public
REVOKE ALL ON [dbo].[sysprotects] to public
REVOKE ALL ON [dbo].[sysreferences] to public
REVOKE ALL ON [dbo].[syssegments] to public
REVOKE ALL ON [dbo].[systasks_view] to public
REVOKE ALL ON [dbo].[systypes] to public
REVOKE ALL ON [dbo].[sysusers] to public
GO
------------------------------------------------------------------------------
-- tempdb: Clear PUBLIC permissions on database.
USE tempdb
GO
REVOKE ALL ON [dbo].[syscolumns] to public
REVOKE ALL ON [dbo].[syscomments] to public
REVOKE ALL ON [dbo].[sysconstraints] to public
REVOKE ALL ON [dbo].[sysdepends] to public
REVOKE ALL ON [dbo].[sysfilegroups] to public
REVOKE ALL ON [dbo].[sysfiles] to public
REVOKE ALL ON [dbo].[sysforeignkeys] to public
REVOKE ALL ON [dbo].[sysfulltextcatalogs] to public
REVOKE ALL ON [dbo].[sysindexes] to public
REVOKE ALL ON [dbo].[sysindexkeys] to public
REVOKE ALL ON [dbo].[sysmembers] to public
REVOKE ALL ON [dbo].[sysobjects] to public
REVOKE ALL ON [dbo].[syspermissions] to public
REVOKE ALL ON [dbo].[sysprotects] to public
REVOKE ALL ON [dbo].[sysreferences] to public
REVOKE ALL ON [dbo].[syssegments] to public
REVOKE ALL ON [dbo].[systypes] to public
REVOKE ALL ON [dbo].[sysusers] to public
GO
----------------------------------------------------------------------------------
-- ADD REQUIRED PERMISSIONS BACK TO MASTER!
use master
GO
GRANT SELECT on spt_values to public
GRANT EXEC on sp_MSHasDBAccess to public
GO
