-- This CLP file was created using ORACLELOOK Version 7.2
-- DATE: Wed 10 June 2002 11:15:48 AM EST
-- Database Name: AWARDS         
-- Database Manager Version:                               
-- Database Codepage:

spool build.log 

----------------------------------------
-- Authorization Statements on Database 
----------------------------------------

CONNECT SYSTEM/MANAGER;

DROP USER EXADMIN CASCADE;
DROP USER JUDGE CASCADE;
DROP USER WEBUSER CASCADE;

GRANT CREATE SESSION, 
      CREATE SEQUENCE, 
      CREATE SYNONYM, 
      CREATE PROCEDURE, 
      CREATE TABLE,
	CREATE TRIGGER 
TO EXADMIN IDENTIFIED BY EXADMIN;

GRANT CREATE SESSION, 
      CREATE SEQUENCE, 
      CREATE SYNONYM,
     CREATE VIEW
TO JUDGE IDENTIFIED BY JUDGE;

GRANT CREATE SESSION, 
      CREATE SEQUENCE, 
      CREATE SYNONYM,
     CREATE VIEW
TO WEBUSER IDENTIFIED BY WEBUSER;

ALTER USER EXADMIN QUOTA UNLIMITED ON USERS;

ALTER USER EXADMIN DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
ALTER USER JUDGE DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
ALTER USER WEBUSER DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;

CONNECT EXADMIN/EXADMIN

------------------------------------------------
-- DDL Statements for table CREDITCARDS
------------------------------------------------

CREATE TABLE CREDITCARDS  (
		  SHORTNAME VARCHAR2(10) NOT NULL , 
		  LONGNAME VARCHAR2(20) NOT NULL ); 

-- DDL Statements for primary key on Table CREDITCARDS

ALTER TABLE CREDITCARDS 
	ADD PRIMARY KEY
		(SHORTNAME);


------------------------------------------------
-- DDL Statements for table RANKINGS
------------------------------------------------
 
 CREATE TABLE RANKINGS  (
		  ID NUMBER NOT NULL, 
		  RANKINGSCORE NUMBER NOT NULL , 
		  RANKINGNAME VARCHAR2(50) NOT NULL , 
		  RANKINGDESCRIPTION VARCHAR2(255) NOT NULL ); 

CREATE SEQUENCE ID_NUMBER;

-- DDL Statements for primary key on Table RANKINGS

ALTER TABLE RANKINGS 
	ADD PRIMARY KEY
		(ID);


------------------------------------------------
-- DDL Statements for table COMPANIES
------------------------------------------------
 
 CREATE TABLE COMPANIES  (
		  ID NUMBER NOT NULL, 
		  COMPANYNAME VARCHAR2(100) NOT NULL , 
		  ADDRESS1 VARCHAR2(50) , 
		  ADDRESS2 VARCHAR2(50) , 
		  CITY VARCHAR2(30) , 
		  STATE VARCHAR2(2) , 
		  ZIP VARCHAR2(15) , 
		  COUNTRY VARCHAR2(30) , 
		  PHONE VARCHAR2(20) , 
		  FAX VARCHAR2(20) , 
		  URL VARCHAR2(100) , 
		  RECORDCREATIONTIMESTAMP DATE , 
		  RECORDMODIFICATIONTIMESTAMP DATE )   
		  ; 

-- DDL Statements for primary key on Table COMPANIES

ALTER TABLE COMPANIES 
	ADD PRIMARY KEY
		(ID);


------------------------------------------------
-- DDL Statements for table PAYMENT
------------------------------------------------
 
 CREATE TABLE PAYMENT  (
		  COMPANYID NUMBER NOT NULL , 
		  CREDITCARDBRAND VARCHAR2(10) , 
		  CREDITCARD RAW(128) , 
		  CREDITCARDEXPIRY RAW(128) , 
		  BILLINGNAME VARCHAR2(30) , 
		  BILLINGADDRESS1 VARCHAR2(30) , 
		  BILLINGADDRESS2 VARCHAR2(30) , 
		  BILLINGCITY VARCHAR2(30) , 
		  BILLINGSTATE VARCHAR2(2) , 
		  BILLINGZIP VARCHAR2(15) , 
		  BILLINGCOUNTRY VARCHAR2(30) , 
		  BILLINGPHONE VARCHAR2(20) , 
		  CHECKPAYMENT CHAR(1) DEFAULT 'N' NOT NULL , 
		  PAYMENTPROCESSEDDATE DATE , 
		  CREDITCARDAUTHORIZATIONCODE VARCHAR2(10) , 
		  CREDITISSUED CHAR(1) DEFAULT 'N' NOT NULL, 
		  CREDITISSUEDDATE DATE , 
		  PAYMENTCOMMENT VARCHAR2(200) , 
		  RECORDCREATIONTIMESTAMP DATE , 
		  RECORDMODIFICATIONTIMESTAMP DATE , 
		  REFUNDISSUED CHAR(1) DEFAULT 'N' NOT NULL, 
		  REFUNDISSUEDTIMESTAMP DATE )   
		  ; 

-- DDL Statements for primary key on Table PAYMENT

ALTER TABLE PAYMENT 
	ADD PRIMARY KEY
		(COMPANYID);


------------------------------------------------
-- DDL Statements for table USERS_COMPANIES
------------------------------------------------
 
 CREATE TABLE USERS_COMPANIES  (
		  USERID VARCHAR2(10) NOT NULL , 
		  COMPANYID NUMBER NOT NULL )   
		  ; 

-- DDL Statements for primary key on Table USERS_COMPANIES

ALTER TABLE USERS_COMPANIES 
	ADD PRIMARY KEY
		(USERID,
		 COMPANYID);


------------------------------------------------
-- DDL Statements for table USERS
------------------------------------------------
 
 CREATE TABLE USERS  (
		  USERID VARCHAR2(10) NOT NULL , 
		  PASSWORD RAW(128) NOT NULL , 
		  USERNAME VARCHAR2(30) , 
		  TITLE VARCHAR2(50) , 
		  COMPANYNAME VARCHAR2(50) , 
		  PHONE VARCHAR2(20) , 
		  EMAIL VARCHAR2(50) NOT NULL , 
		  NOTIFYNEXTYEAR CHAR(1) DEFAULT 'N' NOT NULL, 
		  RECORDCREATIONTIMESTAMP DATE , 
		  RECORDMODIFICATIONTIMESTAMP DATE )   
		  ; 

-- DDL Statements for primary key on Table USERS

ALTER TABLE USERS 
	ADD PRIMARY KEY
		(USERID);


-- DDL Statements for unique constraints on Table USERS

ALTER TABLE USERS 
	ADD UNIQUE
		(EMAIL);

------------------------------------------------
-- DDL Statements for table CATEGORIES
------------------------------------------------
 
 CREATE TABLE CATEGORIES  (
		  ID NUMBER NOT NULL, 
		  CATEGORYHEADING VARCHAR2(100) NOT NULL , 
		  SORTORDER NUMBER NOT NULL , 
		  CATEGORYNAME VARCHAR2(100) NOT NULL , 
		  DESCRIPTION VARCHAR2(1000) NOT NULL , 
		  CRITERIA VARCHAR2(1000) NOT NULL , 
		  LEADJUDGE VARCHAR2(100) , 
		  OTHERJUDGES VARCHAR2(255) , 
		  OBSOLETE CHAR(1) DEFAULT 'N' NOT NULL, 
		  RECORDCREATIONTIMESTAMP DATE DEFAULT SYSDATE NOT NULL , 
		  RECORDMODIFICATIONTIMESTAMP DATE DEFAULT SYSDATE NOT NULL)   
		  ; 
-- DDL Statements for indexes on Table CATEGORIES

CREATE UNIQUE INDEX CATEGORY_UNIQUE ON CATEGORIES 
		(CATEGORYHEADING ASC,
		 CATEGORYNAME ASC);


-- DDL Statements for primary key on Table CATEGORIES

ALTER TABLE CATEGORIES 
	ADD PRIMARY KEY
		(ID);


------------------------------------------------
-- DDL Statements for table PRODUCTS
------------------------------------------------
 
 CREATE TABLE PRODUCTS  (
		  ID NUMBER NOT NULL, 
		  COMPANYID NUMBER NOT NULL , 
		  PRODUCTNAME VARCHAR2(100) NOT NULL , 
		  VERSION VARCHAR2(30) NOT NULL , 
		  ANNOUNCEMENTDATE VARCHAR2(30) NOT NULL , 
		  SHIPDATE VARCHAR2(30) NOT NULL , 
		  URL VARCHAR2(100) , 
		  NDA VARCHAR2(5) NOT NULL , 
		  TARGETAUDIENCE VARCHAR2(2200) NOT NULL , 
		  DESCRIPTION VARCHAR2(4000) NOT NULL , 
		  BUSINESSPROBLEM VARCHAR2(2200) NOT NULL , 
		  COMPETITORS VARCHAR2(2200) NOT NULL , 
		  KEYFEATURES VARCHAR2(4000) NOT NULL , 
		  PRICE VARCHAR2(2200) NOT NULL , 
		  CUSTOMERREFERENCES VARCHAR2(4000) NOT NULL , 
		  CATEGORYID NUMBER , 
		  CATEGORYASSIGNER VARCHAR2(10) , 
		  CATEGORYDATE DATE , 
		  REASSIGNEDCATEGORYID NUMBER , 
		  REASSIGNEDCATEGORYASSIGNER VARCHAR2(10) , 
		  REASSIGNEDCATEGORYDATE DATE , 
		  RANKINGID NUMBER , 
		  RANKINGIDDATE DATE , 
		  RECORDCREATIONTIMESTAMP DATE , 
		  RECORDMODIFICATIONTIMESTAMP DATE , 
		  ORIGINALCATEGORYID NUMBER, 
		  PREVIOUSCATEGORYID NUMBER , 
		  PREVIOUSCATEGORYASSIGNER VARCHAR2(10) , 
		  PREVIOUSCATEGORYTIMESTAMP DATE ); 

-- DDL Statements for primary key on Table PRODUCTS

ALTER TABLE PRODUCTS 
	ADD PRIMARY KEY
		(ID);


------------------------------------------------
-- DDL Statements for table STATES
------------------------------------------------
 
 CREATE TABLE STATES  (
		  COUNTRY VARCHAR2(10) NOT NULL , 
		  COUNTRYSORTORDER NUMBER NOT NULL , 
		  SHORTNAME VARCHAR2(2) NOT NULL , 
		  LONGNAME VARCHAR2(30) NOT NULL )   
		  ; 

-- DDL Statements for primary key on Table STATES

ALTER TABLE STATES 
	ADD PRIMARY KEY
		(COUNTRY,
		 SHORTNAME);


-- DDL Statements for unique constraints on Table STATES

ALTER TABLE STATES 
	ADD UNIQUE
		(SHORTNAME);

------------------------------------------------
-- DDL Statements for table ADMINUSERS
------------------------------------------------
 
 CREATE TABLE ADMINUSERS  (
		  USERID VARCHAR2(10) NOT NULL , 
		  PASSWORD RAW(128) NOT NULL , 
		  ACCESSLEVEL NUMBER NOT NULL , 
		  EMAIL VARCHAR2(50) NOT NULL , 
		  RECORDCREATIONTIMESTAMP DATE DEFAULT SYSDATE NOT NULL, 
		  RECORDMODIFICATIONTIMESTAMP DATE DEFAULT SYSDATE NOT NULL)   
		  ; 

-- DDL Statements for primary key on Table ADMINUSERS

ALTER TABLE ADMINUSERS 
	ADD PRIMARY KEY
		(USERID);


------------------------------------------------
-- DDL Statements for table JUDGES_CATEGORIES
------------------------------------------------
 
 CREATE TABLE JUDGES_CATEGORIES  (
		  USERID VARCHAR2(10) NOT NULL , 
		  CATEGORYID NUMBER NOT NULL , 
		  LEADJUDGE CHAR(1) DEFAULT 'N' NOT NULL)   
		  ; 

-- DDL Statements for primary key on Table JUDGES_CATEGORIES

ALTER TABLE JUDGES_CATEGORIES 
	ADD PRIMARY KEY
		(USERID,
		 CATEGORYID);


-- DDL Statements for unique constraints on Table JUDGES_CATEGORIES

ALTER TABLE JUDGES_CATEGORIES 
	ADD UNIQUE
		(CATEGORYID,
		 LEADJUDGE);

CREATE SYNONYM JUDGES FOR ADMINUSERS;

----------------------------
-- DDL Statements for Views
----------------------------

--------------------------------------------
-- Authorization Statements on Tables/Views 
--------------------------------------------

 
 GRANT SELECT ON ADMINUSERS TO JUDGE    ;
 GRANT INSERT ON CATEGORIES TO JUDGE    ;
 GRANT SELECT ON CATEGORIES TO JUDGE    ;
 GRANT UPDATE ON CATEGORIES TO JUDGE    ;
 GRANT SELECT ON COMPANIES TO JUDGE    ;
 GRANT DELETE ON COMPANIES TO WEBUSER  ;
 GRANT INSERT ON COMPANIES TO WEBUSER  ;
 GRANT SELECT ON COMPANIES TO WEBUSER  ;
 GRANT UPDATE ON COMPANIES TO WEBUSER  ;
 GRANT SELECT ON CREDITCARDS TO WEBUSER  ;
 GRANT SELECT ON JUDGES TO JUDGE    ;
 GRANT INSERT ON PAYMENT TO WEBUSER  ;
 GRANT SELECT ON PAYMENT TO WEBUSER  ;
 GRANT UPDATE ON PAYMENT TO WEBUSER  ;
 GRANT DELETE ON PRODUCTS TO WEBUSER  ;
 GRANT INSERT ON PRODUCTS TO WEBUSER  ;
 GRANT SELECT ON PRODUCTS TO WEBUSER  ;
 GRANT UPDATE ON PRODUCTS TO WEBUSER  ;
 GRANT SELECT ON PRODUCTS TO JUDGE    ;
 GRANT UPDATE ON PRODUCTS TO JUDGE    ;
 GRANT SELECT ON RANKINGS TO JUDGE    ;
 GRANT SELECT ON STATES TO WEBUSER  ;
 GRANT INSERT ON USERS TO WEBUSER  ;
 GRANT SELECT ON USERS TO WEBUSER  ;
 GRANT UPDATE ON USERS TO WEBUSER  ;
 GRANT SELECT ON USERS TO JUDGE    ;
 GRANT SELECT ON USERS_COMPANIES TO JUDGE    ;
 GRANT DELETE ON USERS_COMPANIES TO WEBUSER  ;
 GRANT INSERT ON USERS_COMPANIES TO WEBUSER  ;
 GRANT SELECT ON USERS_COMPANIES TO WEBUSER  ;
 GRANT UPDATE ON USERS_COMPANIES TO WEBUSER  ;


CONNECT WEBUSER/WEBUSER;

create view webuser.creditcards as select * from exadmin.creditcards;
create view webuser.companies as select * from exadmin.companies;
create view webuser.payment as select * from exadmin.payment;
create view webuser.users_companies as select * from exadmin.users_companies;
create view webuser.users as select * from exadmin.users;
create view webuser.products as select * from exadmin.products;
create view webuser.states as select * from exadmin.states;

CONNECT JUDGE/JUDGE;

create view judge.rankings as select * from exadmin.rankings;
create view judge.users as select * from exadmin.users;
create view judge.companies as select * from exadmin.companies;
create view judge.users_companies as select * from exadmin.users_companies;
create view judge.products as select * from exadmin.products;
create view judge.adminusers as select * from exadmin.adminusers;
create view judge.judges as select * from exadmin.judges;
create view judge.categories as select * from exadmin.categories;

CONNECT EXADMIN/EXADMIN;

-- DDL Statements for foreign keys on Table COMPANIES

ALTER TABLE COMPANIES 
	ADD CONSTRAINT SQL020103213209380 FOREIGN KEY
		(STATE)
	REFERENCES STATES
		(SHORTNAME);


-- DDL Statements for foreign keys on Table PAYMENT

ALTER TABLE PAYMENT 
	ADD CONSTRAINT COMPANYID_ID FOREIGN KEY
		(COMPANYID)
	REFERENCES COMPANIES
		(ID);

ALTER TABLE PAYMENT 
	ADD CONSTRAINT SQL020103213759330 FOREIGN KEY
		(BILLINGSTATE)
	REFERENCES STATES
		(SHORTNAME);

ALTER TABLE PAYMENT 
	ADD CONSTRAINT SQL020103214257650 FOREIGN KEY
		(CREDITCARDBRAND)
	REFERENCES CREDITCARDS
		(SHORTNAME);

-- DDL Statements for check constraints on Table PAYMENT

ALTER TABLE PAYMENT 
	ADD CONSTRAINT SQL020103215712130 CHECK 
		(CHECKPAYMENT = 'N' or CHECKPAYMENT = 'Y');

-- DDL Statements for check constraints on Table PAYMENT

ALTER TABLE PAYMENT 
	ADD CONSTRAINT SQL020103215753130 CHECK 
		(REFUNDISSUED = 'N' or REFUNDISSUED = 'Y');


-- DDL Statements for foreign keys on Table USERS_COMPANIES

ALTER TABLE USERS_COMPANIES 
	ADD CONSTRAINT SQL011001051720970 FOREIGN KEY
		(COMPANYID)
	REFERENCES COMPANIES
		(ID);

ALTER TABLE USERS_COMPANIES 
	ADD CONSTRAINT USERID_USERID FOREIGN KEY
		(USERID)
	REFERENCES USERS
		(USERID);


-- DDL Statements for check constraints on Table USERS

ALTER TABLE USERS 
	ADD CONSTRAINT SQL020103215526810 CHECK 
		(NOTIFYNEXTYEAR = 'N' or NOTIFYNEXTYEAR = 'Y');


-- DDL Statements for check constraints on Table CATEGORIES

ALTER TABLE CATEGORIES 
	ADD CONSTRAINT SQL020103220602220 CHECK 
		(OBSOLETE = 'N' or OBSOLETE = 'Y');


-- DDL Statements for foreign keys on Table PRODUCTS

ALTER TABLE PRODUCTS 
	ADD CONSTRAINT SQL011227061046090 FOREIGN KEY
		(ORIGINALCATEGORYID)
	REFERENCES CATEGORIES
		(ID);

ALTER TABLE PRODUCTS 
	ADD CONSTRAINT SQL011227081440480 FOREIGN KEY
		(CATEGORYID)
	REFERENCES CATEGORIES
		(ID);

ALTER TABLE PRODUCTS 
	ADD CONSTRAINT SQL011227081605000 FOREIGN KEY
		(RANKINGID)
	REFERENCES RANKINGS
		(ID);

ALTER TABLE PRODUCTS 
	ADD CONSTRAINT SQL011227091808210 FOREIGN KEY
		(PREVIOUSCATEGORYID)
	REFERENCES CATEGORIES
		(ID);

-- DDL Statements for foreign keys on Table JUDGES_CATEGORIES

ALTER TABLE JUDGES_CATEGORIES 
	ADD CONSTRAINT SQL011228093428261 FOREIGN KEY
		(USERID)
	REFERENCES ADMINUSERS
		(USERID);

ALTER TABLE JUDGES_CATEGORIES 
	ADD CONSTRAINT SQL011228093428280 FOREIGN KEY
		(CATEGORYID)
	REFERENCES CATEGORIES
		(ID);

-- DDL Statements for check constraints on Table JUDGES_CATEGORIES

ALTER TABLE JUDGES_CATEGORIES 
	ADD CONSTRAINT SQL020103220734470 CHECK 
		(LEADJUDGE = 'N' or LEADJUDGE = 'Y');


spool off

