rem set OPENHACK_TARGET=\\erikols-ri2\c$\openhack
set OPENHACK_TARGET=c:\ohacksrc\deploy
set XCOPY_CMD=xcopy /s /y
set XCOPY_OPTIONS=

%XCOPY_CMD% *.aspx %OPENHACK_TARGET% %XCOPY_OPTIONS%
%XCOPY_CMD% *.ascx %OPENHACK_TARGET% %XCOPY_OPTIONS%
%XCOPY_CMD% *.dll %OPENHACK_TARGET% %XCOPY_OPTIONS%
%XCOPY_CMD% *.asax %OPENHACK_TARGET% %XCOPY_OPTIONS%
%XCOPY_CMD% *.css %OPENHACK_TARGET% %XCOPY_OPTIONS%
REM %XCOPY_CMD% *.jpg %OPENHACK_TARGET% %XCOPY_OPTIONS%
%XCOPY_CMD% web.config %OPENHACK_TARGET%
