-- This CLP file was created using DB2LOOK Version 7.1
-- Timestamp: Wed 27 Mar 2002 12:15:48 AM EST
-- Database Name: AWARDS         
-- Database Manager Version:                               
-- Database Codepage: 


CONNECT TO AWARDS;

-- DDL Statements for aliases

CREATE ALIAS "EXADMIN "."JUDGES" FOR "EXADMIN "."ADMINUSERS";


------------------------------------------------
-- DDL Statements for table "EXADMIN "."CREDITCARDS"
------------------------------------------------
 
 CREATE TABLE "EXADMIN "."CREDITCARDS"  (
		  "SHORTNAME" VARCHAR(10) NOT NULL , 
		  "LONGNAME" VARCHAR(20) NOT NULL )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "EXADMIN "."CREDITCARDS"

ALTER TABLE "EXADMIN "."CREDITCARDS" 
	ADD PRIMARY KEY
		("SHORTNAME");


------------------------------------------------
-- DDL Statements for table "EXADMIN "."RANKINGS"
------------------------------------------------
 
 CREATE TABLE "EXADMIN "."RANKINGS"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH +1 , INCREMENT BY +1 , CACHE 20 ) , 
		  "RANKINGSCORE" INTEGER NOT NULL , 
		  "RANKINGNAME" VARCHAR(50) NOT NULL , 
		  "RANKINGDESCRIPTION" VARCHAR(255) NOT NULL )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "EXADMIN "."RANKINGS"

ALTER TABLE "EXADMIN "."RANKINGS" 
	ADD PRIMARY KEY
		("ID");


------------------------------------------------
-- DDL Statements for table "EXADMIN "."COMPANIES"
------------------------------------------------
 
 CREATE TABLE "EXADMIN "."COMPANIES"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH +1 , INCREMENT BY +1 , CACHE 20 ) , 
		  "COMPANYNAME" VARCHAR(100) NOT NULL , 
		  "ADDRESS1" VARCHAR(50) , 
		  "ADDRESS2" VARCHAR(50) , 
		  "CITY" VARCHAR(30) , 
		  "STATE" VARCHAR(2) , 
		  "ZIP" VARCHAR(15) , 
		  "COUNTRY" VARCHAR(30) , 
		  "PHONE" VARCHAR(20) , 
		  "FAX" VARCHAR(20) , 
		  "URL" VARCHAR(100) , 
		  "RECORDCREATIONTIMESTAMP" TIMESTAMP , 
		  "RECORDMODIFICATIONTIMESTAMP" TIMESTAMP )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "EXADMIN "."COMPANIES"

ALTER TABLE "EXADMIN "."COMPANIES" 
	ADD PRIMARY KEY
		("ID");


------------------------------------------------
-- DDL Statements for table "EXADMIN "."PAYMENT"
------------------------------------------------
 
 CREATE TABLE "EXADMIN "."PAYMENT"  (
		  "COMPANYID" INTEGER NOT NULL , 
		  "CREDITCARDBRAND" VARCHAR(10) , 
		  "CREDITCARD" VARCHAR(20) , 
		  "CREDITCARDEXPIRY" VARCHAR(10) , 
		  "BILLINGNAME" VARCHAR(30) , 
		  "BILLINGADDRESS1" VARCHAR(30) , 
		  "BILLINGADDRESS2" VARCHAR(30) , 
		  "BILLINGCITY" VARCHAR(30) , 
		  "BILLINGSTATE" VARCHAR(2) , 
		  "BILLINGZIP" VARCHAR(15) , 
		  "BILLINGCOUNTRY" VARCHAR(30) , 
		  "BILLINGPHONE" VARCHAR(20) , 
		  "CHECKPAYMENT" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		  "PAYMENTPROCESSEDTIMESTAMP" TIMESTAMP , 
		  "CREDITCARDAUTHORIZATIONCODE" VARCHAR(10) , 
		  "CREDITISSUED" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		  "CREDITISSUEDTIMESTAMP" TIMESTAMP , 
		  "PAYMENTCOMMENT" VARCHAR(200) , 
		  "RECORDCREATIONTIMESTAMP" TIMESTAMP , 
		  "RECORDMODIFICATIONTIMESTAMP" TIMESTAMP , 
		  "REFUNDISSUED" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		  "REFUNDISSUEDTIMESTAMP" TIMESTAMP )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "EXADMIN "."PAYMENT"

ALTER TABLE "EXADMIN "."PAYMENT" 
	ADD PRIMARY KEY
		("COMPANYID");


------------------------------------------------
-- DDL Statements for table "EXADMIN "."USERS_COMPANIES"
------------------------------------------------
 
 CREATE TABLE "EXADMIN "."USERS_COMPANIES"  (
		  "USERID" VARCHAR(10) NOT NULL , 
		  "COMPANYID" INTEGER NOT NULL )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "EXADMIN "."USERS_COMPANIES"

ALTER TABLE "EXADMIN "."USERS_COMPANIES" 
	ADD PRIMARY KEY
		("USERID",
		 "COMPANYID");


------------------------------------------------
-- DDL Statements for table "EXADMIN "."USERS"
------------------------------------------------
 
 CREATE TABLE "EXADMIN "."USERS"  (
		  "USERID" VARCHAR(10) NOT NULL , 
		  "PASSWORD" VARCHAR(16) NOT NULL , 
		  "USERNAME" VARCHAR(30) , 
		  "TITLE" VARCHAR(50) , 
		  "COMPANYNAME" VARCHAR(50) , 
		  "PHONE" VARCHAR(20) , 
		  "EMAIL" VARCHAR(50) NOT NULL , 
		  "NOTIFYNEXTYEAR" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		  "RECORDCREATIONTIMESTAMP" TIMESTAMP , 
		  "RECORDMODIFICATIONTIMESTAMP" TIMESTAMP )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "EXADMIN "."USERS"

ALTER TABLE "EXADMIN "."USERS" 
	ADD PRIMARY KEY
		("USERID");


-- DDL Statements for unique constraints on Table "EXADMIN "."USERS"

ALTER TABLE "EXADMIN "."USERS" 
	ADD UNIQUE
		("EMAIL");

------------------------------------------------
-- DDL Statements for table "EXADMIN "."CATEGORIES"
------------------------------------------------
 
 CREATE TABLE "EXADMIN "."CATEGORIES"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH +1 , INCREMENT BY +1 , CACHE 20 ) , 
		  "CATEGORYHEADING" VARCHAR(100) NOT NULL , 
		  "SORTORDER" DOUBLE NOT NULL , 
		  "CATEGORYNAME" VARCHAR(100) NOT NULL , 
		  "DESCRIPTION" VARCHAR(1000) NOT NULL , 
		  "CRITERIA" VARCHAR(1000) NOT NULL , 
		  "LEADJUDGE" VARCHAR(100) , 
		  "OTHERJUDGES" VARCHAR(255) , 
		  "OBSOLETE" CHAR(1) NOT NULL WITH DEFAULT 'N', 
		  "RECORDCREATIONTIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP, 
		  "RECORDMODIFICATIONTIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
		 IN "USERSPACE1" ; 
-- DDL Statements for indexes on Table "EXADMIN "."CATEGORIES"

CREATE UNIQUE INDEX "EXADMIN "."CATEGORY_UNIQUE" ON "EXADMIN "."CATEGORIES" 
		("CATEGORYHEADING" ASC,
		 "CATEGORYNAME" ASC);


-- DDL Statements for primary key on Table "EXADMIN "."CATEGORIES"

ALTER TABLE "EXADMIN "."CATEGORIES" 
	ADD PRIMARY KEY
		("ID");


------------------------------------------------
-- DDL Statements for table "EXADMIN "."PRODUCTS"
------------------------------------------------
 
 CREATE TABLE "EXADMIN "."PRODUCTS"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH +1 , INCREMENT BY +1 , CACHE 20 ) , 
		  "COMPANYID" INTEGER NOT NULL , 
		  "PRODUCTNAME" VARCHAR(100) NOT NULL , 
		  "VERSION" VARCHAR(30) NOT NULL , 
		  "ANNOUNCEMENTDATE" VARCHAR(30) NOT NULL , 
		  "SHIPDATE" VARCHAR(30) NOT NULL , 
		  "URL" VARCHAR(100) , 
		  "NDA" VARCHAR(5) NOT NULL , 
		  "TARGETAUDIENCE" VARCHAR(2200) NOT NULL , 
		  "DESCRIPTION" VARCHAR(5500) NOT NULL , 
		  "BUSINESSPROBLEM" VARCHAR(2200) NOT NULL , 
		  "COMPETITORS" VARCHAR(2200) NOT NULL , 
		  "KEYFEATURES" VARCHAR(5500) NOT NULL , 
		  "PRICE" VARCHAR(2200) NOT NULL , 
		  "CUSTOMERREFERENCES" VARCHAR(5500) NOT NULL , 
		  "CATEGORYID" INTEGER , 
		  "CATEGORYASSIGNER" VARCHAR(10) , 
		  "CATEGORYTIMESTAMP" TIMESTAMP , 
		  "REASSIGNEDCATEGORYID" INTEGER , 
		  "REASSIGNEDCATEGORYASSIGNER" VARCHAR(10) , 
		  "REASSIGNEDCATEGORYTIMESTAMP" TIMESTAMP , 
		  "RANKINGID" INTEGER , 
		  "RANKINGIDTIMESTAMP" TIMESTAMP , 
		  "RECORDCREATIONTIMESTAMP" TIMESTAMP , 
		  "RECORDMODIFICATIONTIMESTAMP" TIMESTAMP , 
		  "ORIGINALCATEGORYID" INTEGER WITH DEFAULT NULL, 
		  "PREVIOUSCATEGORYID" INTEGER , 
		  "PREVIOUSCATEGORYASSIGNER" VARCHAR(10) , 
		  "PREVIOUSCATEGORYTIMESTAMP" TIMESTAMP )   
		 IN "TS_THIRTYTWO" ; 

-- DDL Statements for primary key on Table "EXADMIN "."PRODUCTS"

ALTER TABLE "EXADMIN "."PRODUCTS" 
	ADD PRIMARY KEY
		("ID");


------------------------------------------------
-- DDL Statements for table "EXADMIN "."STATES"
------------------------------------------------
 
 CREATE TABLE "EXADMIN "."STATES"  (
		  "COUNTRY" VARCHAR(10) NOT NULL , 
		  "COUNTRYSORTORDER" DOUBLE NOT NULL , 
		  "SHORTNAME" VARCHAR(2) NOT NULL , 
		  "LONGNAME" VARCHAR(30) NOT NULL )   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "EXADMIN "."STATES"

ALTER TABLE "EXADMIN "."STATES" 
	ADD PRIMARY KEY
		("COUNTRY",
		 "SHORTNAME");


-- DDL Statements for unique constraints on Table "EXADMIN "."STATES"

ALTER TABLE "EXADMIN "."STATES" 
	ADD UNIQUE
		("SHORTNAME");

------------------------------------------------
-- DDL Statements for table "EXADMIN "."ADMINUSERS"
------------------------------------------------
 
 CREATE TABLE "EXADMIN "."ADMINUSERS"  (
		  "USERID" VARCHAR(10) NOT NULL , 
		  "PASSWORD" VARCHAR(16) NOT NULL , 
		  "ACCESSLEVEL" INTEGER NOT NULL , 
		  "EMAIL" VARCHAR(50) NOT NULL , 
		  "RECORDCREATIONTIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP, 
		  "RECORDMODIFICATIONTIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP)   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "EXADMIN "."ADMINUSERS"

ALTER TABLE "EXADMIN "."ADMINUSERS" 
	ADD PRIMARY KEY
		("USERID");


------------------------------------------------
-- DDL Statements for table "EXADMIN "."JUDGES_CATEGORIES"
------------------------------------------------
 
 CREATE TABLE "EXADMIN "."JUDGES_CATEGORIES"  (
		  "USERID" VARCHAR(10) NOT NULL , 
		  "CATEGORYID" INTEGER NOT NULL , 
		  "LEADJUDGE" CHAR(1) NOT NULL WITH DEFAULT 'N')   
		 IN "USERSPACE1" ; 

-- DDL Statements for primary key on Table "EXADMIN "."JUDGES_CATEGORIES"

ALTER TABLE "EXADMIN "."JUDGES_CATEGORIES" 
	ADD PRIMARY KEY
		("USERID",
		 "CATEGORYID");


-- DDL Statements for unique constraints on Table "EXADMIN "."JUDGES_CATEGORIES"

ALTER TABLE "EXADMIN "."JUDGES_CATEGORIES" 
	ADD UNIQUE
		("CATEGORYID",
		 "LEADJUDGE");

----------------------------
-- DDL Statements for Views
----------------------------
create view webuser.creditcards as select * from exadmin.creditcards;
create view webuser.companies as select * from exadmin.companies;
create view webuser.payment as select * from exadmin.payment;
create view webuser.users_companies as select * from exadmin.users_companies;
create view webuser.users as select * from exadmin.users;
create view webuser.products as select * from exadmin.products;
create view judge.rankings as select * from exadmin.rankings;
create view judge.users as select * from exadmin.users;
create view judge.companies as select * from exadmin.companies;
create view judge.users_companies as select * from exadmin.users_companies;
create view webuser.states as select * from exadmin.states;
create view judge.products as select * from exadmin.products;
create view judge.adminusers as select * from exadmin.adminusers;
create view judge.judges as select * from exadmin.judges;
create view judge.categories as select * from exadmin.categories;




-- DDL Statements for foreign keys on Table "EXADMIN "."COMPANIES"

ALTER TABLE "EXADMIN "."COMPANIES" 
	ADD CONSTRAINT "SQL020103213209380" FOREIGN KEY
		("STATE")
	REFERENCES "EXADMIN "."STATES"
		("SHORTNAME")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;


-- DDL Statements for foreign keys on Table "EXADMIN "."PAYMENT"

ALTER TABLE "EXADMIN "."PAYMENT" 
	ADD CONSTRAINT "COMPANYID_ID" FOREIGN KEY
		("COMPANYID")
	REFERENCES "EXADMIN "."COMPANIES"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE "EXADMIN "."PAYMENT" 
	ADD CONSTRAINT "SQL020103213759330" FOREIGN KEY
		("BILLINGSTATE")
	REFERENCES "EXADMIN "."STATES"
		("SHORTNAME")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE "EXADMIN "."PAYMENT" 
	ADD CONSTRAINT "SQL020103214257650" FOREIGN KEY
		("CREDITCARDBRAND")
	REFERENCES "EXADMIN "."CREDITCARDS"
		("SHORTNAME")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

-- DDL Statements for check constraints on Table "EXADMIN "."PAYMENT"

ALTER TABLE "EXADMIN "."PAYMENT" 
	ADD CONSTRAINT "SQL020103215712130" CHECK 
		(CHECKPAYMENT = 'N' or CHECKPAYMENT = 'Y');

-- DDL Statements for check constraints on Table "EXADMIN "."PAYMENT"

ALTER TABLE "EXADMIN "."PAYMENT" 
	ADD CONSTRAINT "SQL020103215753130" CHECK 
		(REFUNDISSUED = 'N' or REFUNDISSUED = 'Y');


-- DDL Statements for foreign keys on Table "EXADMIN "."USERS_COMPANIES"

ALTER TABLE "EXADMIN "."USERS_COMPANIES" 
	ADD CONSTRAINT "SQL011001051720970" FOREIGN KEY
		("COMPANYID")
	REFERENCES "EXADMIN "."COMPANIES"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE "EXADMIN "."USERS_COMPANIES" 
	ADD CONSTRAINT "USERID_USERID" FOREIGN KEY
		("USERID")
	REFERENCES "EXADMIN "."USERS"
		("USERID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;


-- DDL Statements for check constraints on Table "EXADMIN "."USERS"

ALTER TABLE "EXADMIN "."USERS" 
	ADD CONSTRAINT "SQL020103215526810" CHECK 
		(NOTIFYNEXTYEAR = 'N' or NOTIFYNEXTYEAR = 'Y');


-- DDL Statements for check constraints on Table "EXADMIN "."CATEGORIES"

ALTER TABLE "EXADMIN "."CATEGORIES" 
	ADD CONSTRAINT "SQL020103220602220" CHECK 
		(OBSOLETE = 'N' or OBSOLETE = 'Y');


-- DDL Statements for foreign keys on Table "EXADMIN "."PRODUCTS"

ALTER TABLE "EXADMIN "."PRODUCTS" 
	ADD CONSTRAINT "COMPANYID_ID" FOREIGN KEY
		("COMPANYID")
	REFERENCES "EXADMIN "."COMPANIES"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE "EXADMIN "."PRODUCTS" 
	ADD CONSTRAINT "SQL011227061046090" FOREIGN KEY
		("ORIGINALCATEGORYID")
	REFERENCES "EXADMIN "."CATEGORIES"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE "EXADMIN "."PRODUCTS" 
	ADD CONSTRAINT "SQL011227081440480" FOREIGN KEY
		("CATEGORYID")
	REFERENCES "EXADMIN "."CATEGORIES"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE "EXADMIN "."PRODUCTS" 
	ADD CONSTRAINT "SQL011227081605000" FOREIGN KEY
		("RANKINGID")
	REFERENCES "EXADMIN "."RANKINGS"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE "EXADMIN "."PRODUCTS" 
	ADD CONSTRAINT "SQL011227091808210" FOREIGN KEY
		("PREVIOUSCATEGORYID")
	REFERENCES "EXADMIN "."CATEGORIES"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;




-- DDL Statements for foreign keys on Table "EXADMIN "."JUDGES_CATEGORIES"

ALTER TABLE "EXADMIN "."JUDGES_CATEGORIES" 
	ADD CONSTRAINT "SQL011228093428261" FOREIGN KEY
		("USERID")
	REFERENCES "EXADMIN "."ADMINUSERS"
		("USERID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

ALTER TABLE "EXADMIN "."JUDGES_CATEGORIES" 
	ADD CONSTRAINT "SQL011228093428280" FOREIGN KEY
		("CATEGORYID")
	REFERENCES "EXADMIN "."CATEGORIES"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;

-- DDL Statements for check constraints on Table "EXADMIN "."JUDGES_CATEGORIES"

ALTER TABLE "EXADMIN "."JUDGES_CATEGORIES" 
	ADD CONSTRAINT "SQL020103220734470" CHECK 
		(LEADJUDGE = 'N' or LEADJUDGE = 'Y');



--------------------------------------------
-- Authorization Statements on Tables/Views 
--------------------------------------------

 
 GRANT SELECT ON TABLE "JUDGE   "."ADMINUSERS" TO USER "JUDGE   " ;

 GRANT INSERT ON TABLE "JUDGE   "."CATEGORIES" TO USER "JUDGE   " ;

 GRANT SELECT ON TABLE "JUDGE   "."CATEGORIES" TO USER "JUDGE   " ;

 GRANT UPDATE ON TABLE "JUDGE   "."CATEGORIES" TO USER "JUDGE   " ;

 GRANT SELECT ON TABLE "JUDGE   "."COMPANIES" TO USER "JUDGE   " ;

 GRANT DELETE ON TABLE "WEBUSER "."COMPANIES" TO USER "WEBUSER " ;

 GRANT INSERT ON TABLE "WEBUSER "."COMPANIES" TO USER "WEBUSER " ;

 GRANT SELECT ON TABLE "WEBUSER "."COMPANIES" TO USER "WEBUSER " ;

 GRANT UPDATE ON TABLE "WEBUSER "."COMPANIES" TO USER "WEBUSER " ;

 GRANT SELECT ON TABLE "WEBUSER "."CREDITCARDS" TO USER "WEBUSER " ;

 GRANT SELECT ON TABLE "JUDGE   "."JUDGES" TO USER "JUDGE   " ;

 GRANT INSERT ON TABLE "WEBUSER "."PAYMENT" TO USER "WEBUSER " ;

 GRANT SELECT ON TABLE "WEBUSER "."PAYMENT" TO USER "WEBUSER " ;

 GRANT UPDATE ON TABLE "WEBUSER "."PAYMENT" TO USER "WEBUSER " ;

 GRANT CONTROL ON TABLE "EXADMIN "."PRODUCTS" TO USER "EXADMIN " ;

 GRANT DELETE ON TABLE "WEBUSER "."PRODUCTS" TO USER "WEBUSER " ;

 GRANT INSERT ON TABLE "WEBUSER "."PRODUCTS" TO USER "WEBUSER " ;

 GRANT SELECT ON TABLE "WEBUSER "."PRODUCTS" TO USER "WEBUSER " ;

 GRANT UPDATE ON TABLE "WEBUSER "."PRODUCTS" TO USER "WEBUSER " ;

 GRANT SELECT ON TABLE "JUDGE   "."PRODUCTS" TO USER "JUDGE   " ;

 GRANT UPDATE ON TABLE "JUDGE   "."PRODUCTS" TO USER "JUDGE   " ;

 GRANT SELECT ON TABLE "JUDGE   "."RANKINGS" TO USER "JUDGE   " ;

 GRANT SELECT ON TABLE "WEBUSER "."STATES" TO USER "WEBUSER " ;

 GRANT INSERT ON TABLE "WEBUSER "."USERS" TO USER "WEBUSER " ;

 GRANT SELECT ON TABLE "WEBUSER "."USERS" TO USER "WEBUSER " ;

 GRANT UPDATE ON TABLE "WEBUSER "."USERS" TO USER "WEBUSER " ;

 GRANT SELECT ON TABLE "JUDGE   "."USERS" TO USER "JUDGE   " ;

 GRANT SELECT ON TABLE "JUDGE   "."USERS_COMPANIES" TO USER "JUDGE   " ;

 GRANT DELETE ON TABLE "WEBUSER "."USERS_COMPANIES" TO USER "WEBUSER " ;

 GRANT INSERT ON TABLE "WEBUSER "."USERS_COMPANIES" TO USER "WEBUSER " ;

 GRANT SELECT ON TABLE "WEBUSER "."USERS_COMPANIES" TO USER "WEBUSER " ;

 GRANT UPDATE ON TABLE "WEBUSER "."USERS_COMPANIES" TO USER "WEBUSER " ;

---------------------------------------
-- Authorization Statements on Schemas 
---------------------------------------

 
 GRANT CREATEIN ON SCHEMA "JUDGE   " TO USER "JUDGE   " ;

 GRANT CREATEIN ON SCHEMA "JUDGE   " TO USER "EXADMIN " WITH GRANT OPTION;

 GRANT DROPIN ON SCHEMA "JUDGE   " TO USER "EXADMIN " WITH GRANT OPTION;

 GRANT ALTERIN ON SCHEMA "JUDGE   " TO USER "EXADMIN " WITH GRANT OPTION;

 GRANT CREATEIN ON SCHEMA "WEBUSER " TO USER "WEBUSER " ;

 GRANT CREATEIN ON SCHEMA "WEBUSER " TO USER "EXADMIN " ;

 GRANT DROPIN ON SCHEMA "WEBUSER " TO USER "EXADMIN " ;

 GRANT ALTERIN ON SCHEMA "WEBUSER " TO USER "EXADMIN " ;

 GRANT CREATEIN ON SCHEMA "WEBUSER " TO USER "EXADMIN " WITH GRANT OPTION;

 GRANT DROPIN ON SCHEMA "WEBUSER " TO USER "EXADMIN " WITH GRANT OPTION;

 GRANT ALTERIN ON SCHEMA "WEBUSER " TO USER "EXADMIN " WITH GRANT OPTION;

----------------------------------------
-- Authorization Statements on Database 
----------------------------------------

 
 GRANT CREATETAB ON DATABASE  TO USER "EXADMIN " ;

 GRANT BINDADD ON DATABASE  TO USER "EXADMIN " ;

 GRANT CONNECT ON DATABASE  TO USER "EXADMIN " ;

 GRANT CONNECT ON DATABASE  TO USER "WEBUSER " ;

COMMIT WORK;

CONNECT RESET;

TERMINATE;
